### ISSUE TITLE
Can't run app on Amazon AWS instance

### ISSUE THREAD

**Issue by provider161** [opencv/cvat#1009]
Hi! We need to run cvat app on Amazon AWS instance.

I've been using instruction - https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md

I've checked out master branch, with last commit 42aad8b56bcce454b99a852af290d4a9208d37d8

I've added  docker-compose.override.yml file with the next content:

```
version: "2.3"

services:
  cvat:
    environment:
      ALLOWED_HOSTS: "*"
    ports:
      - "8888:8080"
```
8888 - instance's TCP port

So, when I'm going to url: *instance_address*:8888 it redirects me to http://localhost:9080/login which obviously can't be connected.

Have you any idea, what I'm doing wrong? Locally it works fine.
