### ISSUE TITLE
Connection from another computer gives Bad Request(400)

### ISSUE THREAD

**Issue by aurotripathy** [opencv/cvat#102]
My basic install went fine (due to good documentation, thank you!). 
 
_How can I connect from another computer on the LAN?_

I used URL `http://192.168.1.79:8080/` and got a **Bad Request(400)**. 

192.168.1.79 is the IP addr of the "server" machine. 

I also also opened port 8080 on the firewall on the "server" with `ufw`

**Update**, added the lines below to `docker-compose.override.yml`. No effect after reboot.

```
version: "2.3"

services:
  cvat:
    environment:
      ALLOWED_HOSTS: .*
    ports:
      - "80:8080"
```
