### ISSUE TITLE
Could not login from LAN

### ISSUE THREAD

**Issue by yxftju** [opencv/cvat#1093]
I build and run the image using ``ALLOWED_HOST`` but cannot access from LAN 。It shows like this
>Could not check authorization on the server
>Error: Network Error.
but I don't know how to check the logs . 
Can anyone has a solutions?

I have tried the solution as Issue #1011 but it seems doesn't work.
I wanna build an Image for other computers on my computer.

**Comment by bsekachev** [comment]
@yxftju 

We need more information to make suggestions.
Could you please attach config you used?

**Comment by yxftju** [comment]
I use this command to setup my docker 
```
docker-compose -f docker-compose.yml  -f docker-compose.override.yml  -f components/cuda/docker-compose.cuda.yml -f components/openvino/docker-compose.openvino.yml -f components/analytics/docker-compose.analytics.yml -f components/auto_segmentation/docker-compose.auto_segmentation.yml -f components/tf_annotation/docker-compose.tf_annotation.yml -f cvat/apps/dextr_segmentation/docker-compose.dextr.yml -up -d

**Comment by bsekachev** [comment]
Probably you need something like that:

```
  cvat:
    ports:
      - "8080:8080"
    environment:
      ALLOWED_HOSTS: '*'
      UI_HOST: <your_ip>
      UI_PORT: 80

  cvat_ui:
    build:
      args:
        REACT_APP_API_HOST: <your_ip>
        REACT_APP_API_PORT: 8080
    ports:
      - "80:80"
```
You will be able to get CVAT by: ``http://<your_ip>``
Do not forget to clear the browser cache before accessing CVAT. It is important.
