### ISSUE TITLE
Can access CVAT over LAN but not Internet

### ISSUE THREAD

**Issue by LukeAI** [opencv/cvat#1095]
Having followed the instructions here https://github.com/opencv/cvat/issues/1011

 (using local IP and default port 8080) I am able to access CVAT across the LAN. I would like to be able to access CVAT from anywhere using the public IP address and port. What config changes should I make? and how should the NAT port forward be configured?

I did try the above but with our public IP address and an 8080 port forward on the firewall but it didn't work :/

(I have successfully set this up with a previous version of CVAT but I'm a bit confused as to how it works now re. different ports, HOSTS etc.)

My working LAN config.

[base.py.txt](https://github.com/opencv/cvat/files/4117122/base.py.txt)
[docker-compose.override.yml.txt](https://github.com/opencv/cvat/files/4117123/docker-compose.override.yml.txt)
[react_nginx.conf.txt](https://github.com/opencv/cvat/files/4117124/react_nginx.conf.txt)

**Comment by yxftju** [comment]
I could not login over LAN ,can you post your configuration ? I want to have a look .

**Comment by LukeAI** [comment]
> I could not login over LAN ,can you post your configuration ? I want to have a look .

I've done so, but I just followed the instructions in https://github.com/opencv/cvat/issues/1011 and then rebuilt everything. I deleted the volume before rebuilding just to be sure I was purging everything and I don't understand what's going on but probably not necessary.

**Comment by bsekachev** [comment]
@LukeAI 
I agree it might confuse a little
For example we have these ports:

|           | Port over the Internet | LAN port | Port inside Docker  |
|-----------|----------------------|----------|---------------------|
| REST API  | 8060                 | 8070     | 8080                |
| UI SERVER | 7060                 | 7070     | 80                |

Than config file should be:

```
services:
  cvat:
    ports:
      - "8070:8080"
    environment:
      ALLOWED_HOSTS: '*'
      UI_SCHEME: http
      UI_HOST: <your external ip address>
      UI_PORT: 7060
  cvat_ui:
    build:
      args:
        REACT_APP_API_HOST: <your external ip address>
        REACT_APP_API_PORT: 8060
      dockerfile: Dockerfile.ui
    ports:
      - "7070:80"
```

Also you need to trigger port on a router:
```
Internet 8060 => Local 8070
Internet 7060 => Local 7070
```

And setup your firewall for these ports.
