### ISSUE TITLE
[UI] bug when editing a polygon

### ISSUE THREAD

**Issue by adizhol** [opencv/cvat#1187]
while editing a polygon and changing the view (by panning or zooming), the new line is not following the mouse.

**Comment by bsekachev** [comment]
@adizhol Hi, do you do it in development environment?

**Comment by adizhol** [comment]
I was using the master branch

**Comment by bsekachev** [comment]
@adizhol 

I mean, have you installed it with docker or right on your host?

**Comment by adizhol** [comment]
@bsekachev using docker

**Comment by bsekachev** [comment]
@adizhol 

Then could you attach a screenshot with the problem?

**Comment by adizhol** [comment]
![image](https://user-images.githubusercontent.com/13086455/75232453-f04a6980-57bf-11ea-966c-ae35b32a393f.png)

Here, the mouse is not located at the end of the red line

**Comment by adizhol** [comment]
![image](https://user-images.githubusercontent.com/13086455/75232612-30a9e780-57c0-11ea-9118-e6f522561fdd.png)

My mouse in the above screenshot is NOT located at the end of the red line

**Comment by adizhol** [comment]
In addition, you can't close the new edited polygon because you can't click on one of the original points with the mouse.

**Comment by bsekachev** [comment]
@adizhol 

Clearing a cache of the browser might help
If not, have you changed any source code, Dockerfile?

**Comment by adizhol** [comment]
@bsekachev I haven't made any changes

**Comment by bsekachev** [comment]
@adizhol 

I have just done:

```bash
git checkout develop
git pull origin develop
docker-compose run --build
```

Then I went to a job and everything works well.

**Comment by bsekachev** [comment]
@adizhol 

Speaking generally, the problem you described should be fixed by the row:
```dockerfile
RUN patch --binary -p1 < ${HOME}/cvat/apps/engine/static/engine/js/3rdparty.patch
``` 
in Dockerfile.
I don't know why you are experiencing it.

**Comment by adizhol** [comment]
@bsekachev  We already have this in our dockerfile.
This is the commit from where we built: (from Feb 21st)
https://github.com/opencv/cvat/commit/8caa1695c52aab06574fc8651840ff6e80baa072

**Comment by bsekachev** [comment]
@adizhol 

I cannot reproduce it anyway, even from this commit.
My Google Chrome version 74. 
Do you have any exceptions in the browser console? (F12, console tab)
Have you cleared the cache? 
Try to update page by using Shift + F5
What is output of:
```bash
docker exec -it cvat bash -c "cat /home/django/cvat/apps/engine/static/engine/js/3rdparty/svg.draw.js"
```

**Comment by adizhol** [comment]
My Chrome is version 80.
I tried refreshing and clearing cache.
Are you entering the polygon edit mode by holding SHIFT and double-clicking?

[svg.draw.js.txt](https://github.com/opencv/cvat/files/4255416/svg.draw.js.txt)

**Comment by bsekachev** [comment]
@adizhol 

Yes, exactly. 
Your ``svg.draw.js`` looks like the patch I mentioned, wasn't applied. 
And it is a reason of such behavior. Open question is why it wasn't applied. 
I can suggest take a look into build logs

**Comment by adizhol** [comment]
@bsekachev 
[build_log.txt](https://github.com/opencv/cvat/files/4255601/build_log.txt)

**Comment by bsekachev** [comment]
@adizhol 

Hmm.. Nothing suspicious. 
It says patching was done:
```bash
Step 47/53 : RUN patch --binary -p1 < ${HOME}/cvat/apps/engine/static/engine/js/3rdparty.patch
 ---> Running in ccdf9d45907c
patching file cvat/apps/engine/static/engine/js/3rdparty/svg.draggable.js
patching file cvat/apps/engine/static/engine/js/3rdparty/svg.draw.js
patching file cvat/apps/engine/static/engine/js/3rdparty/svg.resize.min.js
patching file cvat/apps/engine/static/engine/js/3rdparty/svg.select.js
Removing intermediate container ccdf9d45907c
```

**Comment by RotemEmergi** [comment]
@bsekachev any update ?

**Comment by bsekachev** [comment]
@RotemEmergi 

Are you also experiencing the issue?

**Comment by RotemEmergi** [comment]
@bsekachev  yes and also pull your latests commit and getting :
![image (5)](https://user-images.githubusercontent.com/15428948/75454528-39e0b300-597e-11ea-96fd-f20401d9e12b.png)

**Comment by bsekachev** [comment]
@RotemEmergi 

So, I see you can't create a task. 
But I don't understand how you problem related with this issue.

**Comment by bsekachev** [comment]
@RotemEmergi 

Okay. Got it. It is one more issue.
Let's do not mix them in one thread.

What is output for you? 
```
docker exec -it cvat bash -c "cat /home/django/cvat/apps/engine/static/engine/js/3rdparty/svg.draw.js"
```

**Comment by bsekachev** [comment]
@RotemEmergi 

Okay. Got it. It is one more issue.
Let's do not mix them in one thread.

What is output for you? 
```
docker exec -it cvat bash -c "cat /home/django/cvat/apps/engine/static/engine/js/3rdparty/svg.draw.js"
```

**Comment by RotemEmergi** [comment]
[sng-draw.txt](https://github.com/opencv/cvat/files/4262303/sng-draw.txt)
@bsekachev

**Comment by bsekachev** [comment]
@RotemEmergi 

What URL do you use to open CVAT? 
Could you share output of ``git status`` and `` git log -n 1`` if you perform them in root CVAT directory?
Could you share docker-compose config that you use to build?

**Comment by RotemEmergi** [comment]
@bsekachev 

```
`On branch develop
Your branch is up-to-date with 'origin/develop'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   cvat/settings/base.py
        modified:   docker-compose.yml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        docker-compose_old.yml

no changes added to commit (use "git add" and/or "git commit -a")`


commit d6e7216c1f9e83569b9917324914a376e43c8f18
Author: Boris Sekachev <40690378+bsekachev@users.noreply.github.com>
Date:   Thu Feb 27 15:59:26 2020 +0300

    React UI: Changing color for a group (#1205)


```

**Comment by bsekachev** [comment]
@RotemEmergi 

What about other questions?

**Comment by RotemEmergi** [comment]
@bsekachev 
use local domain .

and for the compose:
```
version: "2.3"

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10.3-alpine
    ports:
      - "5432:5432"
    networks:
      default:
        aliases:
          - db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db:/var/lib/postgresql/data

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0.5-alpine
    networks:
      default:
        aliases:
          - redis
    restart: always

  cvat:
    container_name: cvat
    image: cvat
    restart: always
    cap_add:
     - SYS_ADMIN
     - MKNOD
    privileged: true
    depends_on:
      - cvat_redis
      - cvat_db
    ports:
      - "8080:8080"
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
        TF_ANNOTATION: "no"
        USER: "django"
        DJANGO_CONFIGURATION: "production"
        WITH_TESTS: "no"
        AUTO_SEGMENTATION: "no"
        TZ: "Etc/UTC"
        OPENVINO_TOOLKIT: "no"
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ""
      UI_SCHEME: http
      UI_HOST: localhost
      UI_PORT: 7080
      ALLOWED_HOSTS: '*'
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - cvat_models:/home/django/models
      - ../cvat/cvat:/home/django/cvat
  cvat_ui:
    container_name: cvat_ui
    image: nginx
    restart: always
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
        REACT_APP_API_PROTOCOL: http
        REACT_APP_API_HOST: localhost
        REACT_APP_API_PORT: 8080
      dockerfile: Dockerfile.ui
    networks:
      default:
        aliases:
          - ui
    depends_on:
      - cvat
    ports:
      - "7080:80"
      
volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_models:
```
