### ISSUE TITLE
Could not check authorization on the server / Could not login on the server (Azure VM)

### ISSUE THREAD

**Issue by kevinanschau** [opencv/cvat#1249]
Hi, I am trying to set up CVAT on a VM on Azure. I followed the [Installation Guide](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#ubuntu-1804-x86_64amd64) and the [AWS-Deployment Guide](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/AWS-Deployment-Guide.md). My `docker-compose.override.yml` file has the following in it

```yml
version: "2.3"

services:
  cvat:
    environment:
      ALLOWED_HOSTS: "*"
      UI_SCHEME: http
      UI_HOST: <public_ip>
      UI_PORT: 80
    ports:
      - "7080:8080"
  
  cvat_ui:
    build:
      args:
        REACT_APP_API_PROTOCOL: http
        REACT_APP_API_HOST: <public_ip>
        REACT_APP_API_PORT: 7080
    ports:
      - "80:80"
```

I am able to build with `docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d --build`, but get a warning saying

```bash
[Warning] One or more build-args [REACT_APP_API_PROTOCOL REACT_APP_API_HOST REACT_APP_API_PORT] were not consumed
```

However, I can connect to my VM on Azure either through `<public_ip>:7080` or `<public_ip>:80`. I see the login page but get an error and cannot log into the superuser. See the image below.

![loginpage_error](https://user-images.githubusercontent.com/17898166/76426237-128cdb80-63ab-11ea-9e47-423d5343f399.png)

For reference, I am on the commit `7050ad4` and have opened the following ports on my VM on Azure

![azure_inboundportrules](https://user-images.githubusercontent.com/17898166/76427204-4fa59d80-63ac-11ea-9c7d-fb233aeabaee.png)

I appreciate any help. Thanks 👋
