### ISSUE TITLE
local to public ip change

### ISSUE THREAD

**Issue by vasanththangavel** [opencv/cvat#1555]
cvat tool works fine in localhost:8080 in ubuntu 18.04 but when try to change it to public ip it won't do anything, i followed all the instruction given in installation page. i did override yml file likes this

```
# docker-compose.override.yml 
version: "2.3"

services:
  cvat_proxy:
    environment:
      CVAT_HOST: '152.21.5.214'
    ports:
    - "80:3365"
    
  cvat:
    environment:
      ALLOWED_HOSTS: '*'
```

**Comment by azhavoro** [comment]
@vasanththangavel Hi
format of ports option should be ```your public port:80``` i.e., you should not change the internal port.
```
cvat_proxy:
    environment:
      CVAT_HOST: '152.21.5.214'
    ports:
    - "3365:80"
```
Please use gitter for such questions in the future, also this guide my be usefull https://docs.docker.com/compose/networking/
