### ISSUE TITLE
Failed to create a task with a large data set: no space left on device

### ISSUE THREAD

**Issue by davidsblom** [opencv/cvat#203]
The following error is shown in the interface.
```
Could not create the task. distutils.errors.DistutilsFileError: could not write to '/home/django/data/2/.upload/upload-19-11-2018/jimmy/Isolatie/DSC00406.JPG': No space left on device
```

What is the recommended way to increase the storage capacity with the docker container? I'm already using a shared drive as discussed here: https://github.com/opencv/cvat#share-path

**Comment by davidsblom** [comment]
I managed to get it working by using a separate volume for the data as follows:

``` yaml
version: "2.3"

services:
  cvat:
    volumes:
      - cvat_share:/home/django/share:ro
      - cvat_data:/home/django/data
    environment:
      CVAT_SHARE_URL: "Shared directory"
    ports:
      - "80:8080"

volumes:
  cvat_data:
    driver_opts:
      type: none
      device: /home/david/data
      o: bind
  cvat_share:
    driver_opts:
      type: none
      device: /home/david/shared_data
      o: bind
```
