### ISSUE TITLE
Can't mount data (share_path)

### ISSUE THREAD

**Issue by dasmehdix** [opencv/cvat#2263]
Hi. I am newbie about docker usage. I have a dataset with lots of photos. I want to label them into CVAT. As mentioned in [doc](https://github.com/openvinotoolkit/cvat/blob/develop/cvat/apps/documentation/installation.md#share-path), I should mount my dataset into docker. I tried multiple things. I edit and rebuilded `docker-compose.yml` and `docker-composo.override.yml` but still docker can't acces my dataset. My OS is Windows 10 with WSL2. In the example `share_path`, the path is `/mnt/share`. Do  I need to give path of my dataset like `C:/Users/Desktop/.../` or do I need to give path of WSL2 for windows?

**Comment by jackneil** [comment]
Hi @dasmehdix. Here's how I got it to work in docker-compose.override.yml:
version: "2.3"
services:
  cvat:
    environment:
      CVAT_SHARE_URL: "Mounted from the e:\\VoTT host directory"
    volumes:
      - type: bind
        source: "e:\\VoTT"
        target: /home/django/share

just replace with your source location

**Comment by dasmehdix** [comment]
> Hi @dasmehdix. Here's how I got it to work in docker-compose.override.yml:
> 
> > version: "2.3"
> > services:
> > cvat:
> > environment:
> > CVAT_SHARE_URL: "Mounted from the e:\VoTT host directory"
> > volumes:
> > - type: bind
> > source: "e:\VoTT"
> > target: /home/django/share
> 
> just replace with your source location. and make sure your indentation is right since github is flattening them

Let's say my dataset is in path `C:\Users\XX\Desktop\YY` in windows enviroment.

> 
> > version: "2.3"
> > services:
> > cvat:
> > environment:
> > CVAT_SHARE_URL: "Mounted from the C:\Users\XX\Desktop\YY host directory"
> > volumes:
> > - type: bind
> > source: "C:\Users\XX\Desktop\YY"
> > target: /home/django/share
> 
So, is this configuration true for my enviroment?
BTW, thanks for answer.

**Comment by bsekachev** [comment]
> do I need to give path of WSL2 for windows

I suppose, yes. Since you run docker under WSL, you need to provide path in WSL.
BTW, we updated docker-compose version to 3.3 in develop branch, just for your information.

**Comment by veer5551** [comment]
Hello,

Using CVAT directly in Windows 10 (without WSL).
Tried mounting data and encountered the following errors.

`ERROR: for cvat  Cannot create container for service cvat: failed to mount local volume: mount E:\e\cvat_data:/var/lib/docker/volumes/cvat_cvat_share/_data, flags: 0x1000: no such file or directory`

My `docker-compose.override.yml` file

```
version: "2.3"
services:
  cvat_proxy:
    environment:
      CVAT_HOST: "localhost"

  cvat:
    environment:
      CVAT_SHARE_URL: "Mounted from /e/cvat_data host directory"
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /e/cvat_data
      o: bind
```
Tried all possible combinations for the paths representations, but still can't mount the storage!
Could you please have a look?

Thanks a lot!

**Comment by jackneil** [comment]
If you’re doing it with hyperv you need to go into docker and share that directory with the docker instance

Jack Neil
CEO / Hank AI, Inc.
jack.neil@hank.ai
(w) +1.904.GET.HANK
(m) +1.803.466.7551

Sent via Superhuman iOS ( https://sprh.mn/?vip=jack.neil@hank.ai )

**Comment by veer5551** [comment]
Yes @jackneil, that was the first thing I did.
I wonder, I was able to successfully mount Data with **same override** file with **previous version of CVAT**.

Need to look a little deeper into the issue I guess!
Thanks!

**Comment by veer5551** [comment]
Hello, 

Having hard time figuring it out!
Below is the Image showing Error + File Sharing enabled in Docker Desktop + compose.override file

![image](https://user-images.githubusercontent.com/41330355/97308267-b23da200-1886-11eb-8cb7-0eb8b43950bd.png)

Has any one figured it out?
Am missing something ?

Thanks a lot!

**Comment by ChrisCurrin** [comment]
this seemed to work for me:

1. create a volume

```bash
docker volume create --name cvat_share --opt type=none --opt device=/home/cbc/my_shared_folder --opt o=bind
```

2. tell docker to search for a volume created externally
```
# docker-compose.override.yml
version: "3.3"

services:
  cvat:
    environment:
      CVAT_SHARE_URL: ""
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    external: true
```

**Comment by veer5551** [comment]
Hey @ChrisCurrin,
Thanks a lot!! That worked Effortlessly!
Saved me!

Thanks!

**Comment by tralfamadude** [comment]
I tried what @ChrisCurrin suggests and it did not work for ver. 3.3. Previously I tried what is documented in https://github.com/openvinotoolkit/cvat/blob/master/cvat/apps/documentation/installation.md#share-path

The symptom of "did not work" is that when trying to create a task, I pick Connected File Share tab and I see "No data". 

It would be nice to have a command to validate the setup to come at this another way. (Even better, it would be nice to have it work.)

Any suggestions?

**Comment by ipesanz** [comment]
In adition to @ChrisCurrin answer: Keep the `cvat_share:/home/django/share:ro` line as it is.... as it's referring to django and not your shared path

**Comment by ChrisCurrin** [comment]
"cbc" is just my linux username.

If you're on windows, it may be
"device=/mnt/c/share"

**Comment by isudos** [comment]
I did this:

> this seemed to work for me:
> 
> 1. create a volume
> 
> ```shell
> docker volume create --name cvat_share --opt type=none --opt device=/home/cbc/my_shared_folder --opt o=bind
> ```
> 
> 2. tell docker to search for a volume created externally
> 
> ```
> # docker-compose.override.yml
> version: "3.3"
> 
> services:
>   cvat:
>     environment:
>       CVAT_SHARE_URL: ""
>     volumes:
>       - cvat_share:/home/django/share:ro
> 
> volumes:
>   cvat_share:
>     external: true
> ```

and got 
`ERROR: for 4925b50df6a1_cvat  Cannot create container for service cvat: open /var/lib/docker/volumes/cvat_share/_data: permission denied`

I tried to make it 777 and still got same error. 
What can cause this?

**Comment by kimlia545** [comment]
@ChrisCurrin 

docker-compose -f docker-compose.yml -f docker-compose.override.yml up
ERROR: .IOError: [Errno 2] No such file or directory: u'./docker-compose.override.yml'
![image](https://user-images.githubusercontent.com/72369991/153341191-21eacde5-86e1-44b2-9e76-8a4e9af9c433.png)
How do I create 'docker-compose.override.yml'?

In case of Windows 
docker volume create --name cvat_share --opt type=none --opt device=/mnt/c/share --opt o=bind

# docker-compose.override.yml
version: "3.3"

services:
  cvat:
    environment:
      CVAT_SHARE_URL: ""
    volumes:
      - cvat_share:/mnt/c/share

volumes:
  cvat_share:
    external: true

**Comment by gamingflexer** [comment]
This seemed to work for me on **Mac M1**:

In `docker-compose.yml` file i made the following changes and also thanks to @c00lcoder for the commands

In services & cvat_utils
```
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - cvat_share:/home/django/share:ro
```

& added this

```
volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_share:
    external: true

```

On terminal 

```
docker volume create --name cvat_share --opt type=none --opt device=/Users/cosmos/Desktop/Projects/Resume Parser/img_annotations --opt o=bind
```
`docker-compose up -d`

Delete the container, prune other volumes if needed and restart docker if this fails

**Comment by terancejiang** [comment]
> this seemed to work for me:
> 
> 1. create a volume
> 
> ```shell
> docker volume create --name cvat_share --opt type=none --opt device=/home/cbc/my_shared_folder --opt o=bind
> ```
> 
> 2. tell docker to search for a volume created externally
> 
> ```
> # docker-compose.override.yml
> version: "3.3"
> 
> services:
>   cvat:
>     environment:
>       CVAT_SHARE_URL: ""
>     volumes:
>       - cvat_share:/home/django/share:ro
> 
> volumes:
>   cvat_share:
>     external: true
> ```

work like a charm

**Comment by aerdos** [comment]
For some reason none of the above, or [the official docs](https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path) worked for me. Instead I had to use a combination.

1. Create a `docker-compose.override.yml` file in the `cvat` directory. Note that my definition of the `cvat_share` section differs from the official docs.
```yml
# docker-compose.override.yml
services:
    cvat_server:
        volumes:
            - cvat_share:/home/django/share:ro
    cvat_worker_import:
        volumes:
            - cvat_share:/home/django/share:ro
    cvat_worker_export:
        volumes:
            - cvat_share:/home/django/share:ro
    cvat_worker_annotation:
        volumes:
            - cvat_share:/home/django/share:ro

volumes:
    cvat_share:
        external: true
```

2. Create a `C:\work_share` directory (modify as necessary) and create a Docker volume from it.
```
docker volume create --name cvat_share --opt type=none --opt device=C:\work_share --opt o=bind
```

3. Build
```
docker compose -f .\docker-compose.yml -f .\docker-compose.override.yml up -d --build
```

Not sure why the other ideas didn't work for me 🤷, insight appreciated.

**Comment by SaeedAID** [comment]
For everyone's benefit, this solution worked perfectly for me:

- **Ubuntu Version:** 22.04
- **CVAT Server Version:** 2.19.1

In the `docker-compose.yml`, near the end, you will find the following volume declarations:

```
volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_inmem_db:
  cvat_events_db:
  cvat_cache_db:
```
Additionally, I have a shared folder mounted at `/mnt/volume_cvat_01`. To store the CVAT volumes, I created a directory named `cvat_volumes` and set up subdirectories for each volume as follows:

```
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_db
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_data
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_keys
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_logs
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_inmem_db
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_events_db
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_cache_db
```
I then updated the `docker-compose.yml` file with the following volume configurations:

```
volumes:
  cvat_db:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_db
      o: bind
  cvat_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_data
      o: bind
  cvat_keys:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_keys
      o: bind
  cvat_logs:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_logs
      o: bind
  cvat_inmem_db:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_inmem_db
      o: bind
  cvat_events_db:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_events_db
      o: bind
  cvat_cache_db:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_cache_db
      o: bind
```
Finally, set the CVAT host environment variable and start the container:

```
export CVAT_HOST=FQDN_or_YOUR-IP-ADDRESS
docker compose -f docker-compose.yml up -d
```
After that, you can access CVAT using your specified `CVAT_HOST`. Create a project, and navigate to `/mnt/volume_cvat_01/cvat_volumes/cvat_data/projects` to see the created project number.
