### ISSUE TITLE
Increase frame buffer / improve the way buffering is handled

### ISSUE THREAD

**Issue by mrKallah** [opencv/cvat#3798]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I am trying to increase the amount of buffered frames on a local server run for multiple user annotations, I've tried to find this in the docs and I've asked on glitter, but with no luck. The reason I need to increase the buffer is due to having usually ~1k-10k frames between the end of one annotation to the start of the next. The data I am working with is mostly without the subject I'm trying to detect. It would significantly increase my productivity for the buffer handling to be improved. 

### Expected Behaviour

The server should have a setting to change the amount of frames buffered so if you are running a dedicated server to annotate, you can use it how you wish. 
When the client goes to the next frame, the server should start to send the next buffered frame to the client. 
Personally I'd like it if the server would work at 100% CPU when loading frames to minimize the time spent waiting for the server to load frames. 

### Current Behaviour

For my use-case, the server is idle until the client runs out of frames, then it loads frames using ~25% of CPU or 100% of one core and then it goes idle again until the clients buffer is empty. I can also not find a setting to change the amount of frames buffered. 

### Possible Solution

Short Term - Add a setting for the buffered frames. 
Long Term - Re-write the way the buffering of images is handled and allow for multithreaded frame buffering to utilize parallelism

### Steps to Reproduce (for bugs)

1. Load a large dataset with somewhat high resolution
2. Hold down f or v to fast forward
3. After a little while it should start loading for a few seconds

### Context

This issue drastically decreases productivity of our team when annotating our dataset. We are trying to annotate rare occurrences in usually 1.5h videos, where there is sometimes less than 5 separate annotation tracks. The video needs to be relatively high resolution due to the nature of what we are trying to detect. Thus we are stuck spending a lot of time waiting for the machine to load the next frames. 

### Your Environment

- Git hash commit (`git log -1`): e8b328488257b41d8444a4d87ee6da62fedf072c
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.9
- Are you using Docker Swarm or Kubernetes? unsure, I've installed it as per https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/ for ubuntu
- Operating System and version (e.g. Linux, Windows, MacOS): Linux Ubuntu
- Code example or link to GitHub repo or gist to reproduce problem:
#docker.compose.overide.yml
```
# Copyright (C) 2018-2021 Intel Corporation
#
# SPDX-License-Identifier: MIT

#version: '3.3'

version: '3.3'


services:
  cvat:
    environment:
      CVAT_SHARE_URL: "Mounted from /mnt/share host directory"
      CVAT_HOST: "localhost 192.168.10.135"
    volumes:
      - cvat_share:/home/django/share:ro
    labels:
      - traefik.http.routers.cvat.rule=(Host(`localhost`) || Host(`192.168.10.135`)) &&
          PathPrefix(`/api/`, `/git/`, `/opencv/`, `/analytics/`, `/static/`, `/admin`, `/documentation/`, `/django-rq`)

  cvat_ui:
    labels:
      - traefik.http.routers.cvat-ui.rule=Host(`localhost`) || Host(`192.168.10.135`)

  traefik:
    ports:
      - 80:8080
      - 90:9090

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /mnt/share
      o: bind
```

docker.compose.yml
```
# Copyright (C) 2018-2021 Intel Corporation
#
# SPDX-License-Identifier: MIT

version: '3.3'

services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db:/var/lib/postgresql/data
    networks:
      - cvat

  cvat_redis:
    container_name: cvat_redis
    image: redis:4.0-alpine
    restart: always
    networks:
      - cvat

  cvat:
    container_name: cvat
    image: openvino/cvat_server
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ''
      ALLOWED_HOSTS: '*'
      CVAT_REDIS_HOST: 'cvat_redis'
      CVAT_POSTGRES_HOST: 'cvat_db'
      ADAPTIVE_AUTO_ANNOTATION: 'false'
    labels:
      - traefik.enable=true
      - traefik.http.services.cvat.loadbalancer.server.port=8080
      - traefik.http.routers.cvat.rule=Host(`${CVAT_HOST:-localhost}`) &&
          PathPrefix(`/api/`, `/git/`, `/opencv/`, `/analytics/`, `/static/`, `/admin`, `/documentation/`, `/django-rq`)
      - traefik.http.routers.cvat.entrypoints=web
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
    networks:
      - cvat

  cvat_ui:
    container_name: cvat_ui
    image: openvino/cvat_ui
    restart: always
    depends_on:
      - cvat
    labels:
      - traefik.enable=true
      - traefik.http.services.cvat-ui.loadbalancer.server.port=80
      - traefik.http.routers.cvat-ui.rule=Host(`${CVAT_HOST:-localhost}`)
      - traefik.http.routers.cvat-ui.entrypoints=web
    networks:
      - cvat

  traefik:
    image: traefik:v2.4
    container_name: traefik
    restart: always
    command:
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=cvat"
      - "--entryPoints.web.address=:8080"
    # Uncomment to get Traefik dashboard
    #   - "--entryPoints.dashboard.address=:8090"
    #   - "--api.dashboard=true"
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.dashboard.entrypoints=dashboard
    #   - traefik.http.routers.dashboard.service=api@internal
    #   - traefik.http.routers.dashboard.rule=Host(`${CVAT_HOST:-localhost}`)
    ports:
      - 8080:8080
      - 8090:8090
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - cvat

volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:

networks:
  cvat:


```
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.
