### ISSUE TITLE
 Access connected file share from NFS mounted storage

### ISSUE THREAD

**Issue by rajaasokan** [opencv/cvat#4699]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I have mounted an Azure Storage container to an Ubuntu 18.04 VM following [official documentation](https://docs.microsoft.com/en-us/azure/storage/blobs/network-file-system-protocol-support-how-to). 
Then I updated docker compose file (docker-compose.override.yml) by following CVAT [official documentation](https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#share-path) for mounting share storage to CVAT docker and [docker-compose documentation](https://docs.docker.com/compose/compose-file/compose-file-v3/#driver_opts) as follows:  
```
version: '3.3'

services:
  cvat:
    environment:
      CVAT_SHARE_URL: 'Mounted from /mnt/share host directory'
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: "nfs"
      device: ":/mnt/share"
      o: "addr=10.40.0.199,nolock,soft,rw"
```
Then I install CVAT following [installation guide](https://openvinotoolkit.github.io/cvat/docs/administration/basics/installation/#ubuntu-1804-x86_64amd64). But we I try to run the CVAT docker using the command `docker-compose up -d`, getting following error:
```
ERROR: for cvat  Cannot create container for service cvat: failed to mount local volume: mount :/mnt/share:/opt/docker/volumes/cvat_cvat_share/_data, data: addr=10.40.0.199,nolock,soft: operation not supported

ERROR: Encountered errors while bringing up the project.
```
I tried different changes in the config file, but no luck. The [CVAT documentation](https://openvinotoolkit.github.io/cvat/docs/administration/advanced/mounting_cloud_storages/#microsoft-azure-container-as-filesystem) says you can mount the cloud storage as FUSE and use it later as share. But does it only support fuse protocol? How can I use a cloud storage mounted using NFS protocol in CVAT tool?

### Steps to Reproduce (for bugs)

1. Mount Azure Blob storage container to Linux VM (Ubuntu 18.04) using NFS3 protocol
2. Update the `docker-compose.override.yml` as above
3. Follow the CVAT installation guide for Ubuntu
4. `docker-compose up -d`

### Context

We are trying to use Image/video files from Azure Storage container mounted using NFS protocol. 
Project is kind of affected by this issue. This may stop us using CVAT as annotation tool.

### Your Environment

- Docker version `docker version` : 20.10.17
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Linux Ubuntu 18.04

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by salinaaaaaa** [comment]
Any luck on this?

**Comment by yossibiton** [comment]
I got the same error. 
My data is on "/efs", and i try to share it by setting these lines (following [this](https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path) guide) :

```
services:
  cvat_server:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_default:
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /efs
      o: bind
```


When i run "docker-compose up -d" i get this error : 
`ERROR: for cvat_worker_default  Cannot create container for service cvat_worker_default: failed to mount local volume: mount /efs:/var/snap/docker/common/var-lib-docker/volumes/cvat_cvat_share/_data, flags: 0x1000: no such file or directory`
