### ISSUE TITLE
Database is locked while running 'docker-compose up'

### ISSUE THREAD

**Issue by raihan1319** [opencv/cvat#4720]
Hi,

 So recently I have been trying to implement CVAT on my company's server. I tried to do it in two ways,

1. Pull from openvinotoolkit/cvat and fix the merge issue.
2. Build it from scratch b cloning it from openvinotoolkit/cvat.

Regardless of which step I followed when I tried to run **docker-compose up -d** it says the database is locked (please see snapshot for details). I have tried many things to resolve this issue but nothing works.

The company is using Azure for remote storage.

I am willing to provide more information if needed.
![Screenshot from 2022-06-24 13-20-49](https://user-images.githubusercontent.com/99178784/175896338-a71ec2f7-6764-4756-bb4a-931c9e20ff14.png)

**Comment by chaoyifei** [comment]
sqlite3 will be problems with multi process writing， please use postgres

**Comment by raihan1319** [comment]
> sqlite3 will be problems with multi process writing， please use postgres

Yes, I thought about it. But isn't having it in the docker-compose.yml file enough? Or do I need to change it somewhere else for example in manage.py?

The issue is, in the first build there was no problem. But when I tried to update the server and then access the database the error occurred.

![Screenshot from 2022-08-23 13-01-32](https://user-images.githubusercontent.com/99178784/186142573-18fb9ac7-4287-4fc4-827b-330e28c31906.png)

**Comment by chaoyifei** [comment]
your Django_CONFIGURATION is  production?

cvat:
    ····
   args:
        Django_CONFIGURATION:production

**Comment by chaoyifei** [comment]
your Django_CONFIGURATION is  production?

cvat:
    ····
   args:
        Django_CONFIGURATION:production

**Comment by chaoyifei** [comment]
use docker-compose-dev.yml build image

```
docker-compose -f docker-compose-dev.yml build 
```

**Comment by azhavoro** [comment]
This is defenetly discashe db issue and is not realted with CVAT database. 
Don't store `/home/django/data/cache` container folder on NFS storages.
https://www.sqlite.org/faq.html#q5

For now, try adding a new docker volume located on non-NFS storage, but make sure the cvat container user (uid, guid 1000:1000) has write permissions
Like this:
```yaml
services:
  cvat:
    volumes:
      - cvat_cache:/home/django/data/cache
```

**Comment by titarch** [comment]
Thanks @azhavoro, that did the trick for me.
I am using helm release with an NFS storage, I just mounted a separate pvc using the `cvat.backend.server.additionalVolumes` and `cvat.backend.server.additionalVolumeMounts` values and that resolved the issue.
This locking issue was making my dashboard very slow to load.
I would be great to have a warning about using NFS as the cvat-backend-data storage in the docs, the symptoms where not so easy to understand as it was just making the dashboard very slow to load and by looking at the network it seemed that some random api endpoints were just very slow to load.

Here is my override yaml if that can help anyone:
```
cvat:
  backend:
    image: replace-with-your-image
    defaultStorage:
      enabled: true
      type: azure # I modified the chart to mount a pvc using nfs
    server:
      additionalVolumeMounts:
        - name: cvat-cache-data
          mountPath: /home/django/data/cache
      additionalVolumes:
        - name: cvat-cache-data
          persistentVolumeClaim:
            claimName: cvat-cache-data
```
You will also need to create the pvc of course.
