### ISSUE TITLE
change in  cvat_share not reflecting.

### ISSUE THREAD

**Issue by vikaschouhan** [opencv/cvat#479]
Hi,
According to documentation to change cvat_share as mentioned below
```
version: "2.3"

services:
  cvat:
    environment:
      CVAT_SHARE_URL: "Mounted from /mnt/share host directory"
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /mnt/share
      o: bind
```
I added the following in docker-compose.override.yml.
```
version: "2.3"

services:
  cvat:
    environment:
      CVAT_SHARE_URL: "Mounted from /mnt/vol0/shared/ host directory"
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /mnt/vol0/shared/
      o: bind
```
I could immediately see the items inside _/mnt/vol0/shared_ being reflected while creating new task with **"Source"** pointing to **"Share"**.
But, when I tried to change _/mnt/vol0/shared_ to something else, the items in new location are not being reflected and task creation process is showing same items as in old path.
Could anyone please help me on this ?

P.S. I am using the latest github repo of cvat.
