### ISSUE TITLE
Help with loading custom Yolov5 model trained with Objects365 onto CVAT

### ISSUE THREAD

**Issue by gd1925** [opencv/cvat#4798]
Hello, 

I have a custom YOLOv5 model which is trained on Objects365 dataset and I wish to use it on CVAT for auto-annotation feature. I have been following the tutorial - [https://openvinotoolkit.github.io/cvat/docs/manual/advanced/serverless-tutorial/](url) and I am not sure how to load the model in main.py. I have the model on my PC and I wish to give the path which I saw on some of the model_handler.py, but I am very confused about the correct way of loading it. So far, on running the command - serverless/deploy_gpu.sh serverless/pytorch/ultralytics/yolov5/, I get the following error - 
![image](https://user-images.githubusercontent.com/50822928/183861998-d3d69519-6f56-4f2c-8fae-ccc2f1a495ed.png)

Could you please guide me in how I should load the model correctly?

**Comment by bsekachev** [comment]
@gd1925 

>  I have the model on my PC and I wish to give the path which I saw

In general you need to put your model file into Docker image of the serverless function. 
To move it there, you can setup corresponding installation steps in ``function.yml``.

For example for Deep extreme cut we have:

```
      postCopy:
        - kind: RUN
          value: curl -O https://download.01.org/openvinotoolkit/models_contrib/cvat/dextr_model_v1.zip
        - kind: RUN
          value: unzip dextr_model_v1.zip
```

and in model-handler.py:

```
        base_dir = os.path.abspath(os.environ.get("MODEL_PATH", "/opt/nuclio"))
        model_xml = os.path.join(base_dir, "dextr.xml")
        model_bin = os.path.join(base_dir, "dextr.bin")
        self.model = ModelLoader(model_xml, model_bin)
```

Previously we have uploaded the model to a cloud, you can do the same.
Or you can use COPY directive to copy model from your local filesystem,  or you can somehow mount a dir from your file system to corresponding docker container (this way may be not easy), there are different ways to do that.
