### ISSUE TITLE
Broken helm chart - if using custom release name

### ISSUE THREAD

**Issue by gecube** [opencv/cvat#5186]
Good day!

I am trying to install the cvat with the helm. I am using FluxCD for the automation of process and the next Helm Release object:

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cvat
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/opencv/cvat
  ref:
    tag: v2.2.0
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cvat
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helm-chart
      sourceRef:
        kind: GitRepository
        name: cvat
  install:
    createNamespace: true
  targetNamespace: cvat2
  interval: 1m0s
  values:
    postgresql:  
      secret:
        password: [REDACTED]
        postgres_password: [REDACTED]
        replication_password: [REDACTED]
```

In fact, all necessary objects are created:

```
kubectl get pods -n cvat2
NAME                                                 READY   STATUS                       RESTARTS          AGE
cvat2-cvat-backend-server-58b7bf4bd9-tn8rl           0/1     Init:0/1                     0                 13h
cvat2-cvat-backend-utils-6df54b95b7-vf7gq            1/1     Running                      0                 13h
cvat2-cvat-backend-worker-default-6688c7657c-92pbw   1/1     Running                      0                 13h
cvat2-cvat-backend-worker-default-6688c7657c-k6c6q   1/1     Running                      0                 13h
cvat2-cvat-backend-worker-low-59684c8549-wg5n6       1/1     Running                      0                 13h
cvat2-cvat-frontend-85bc8767d9-g6ckd                 1/1     Running                      0                 13h
cvat2-cvat-opa-5756f7d597-56nm5                      0/1     CrashLoopBackOff             150 (3m32s ago)   13h
cvat2-cvat-postgresql-0                              0/1     CreateContainerConfigError   0                 100m
cvat2-cvat-redis-master-0                            1/1     Running                      0                 13h
cvat2-cvat-redis-replicas-0                          1/1     Running                      0                 13h
cvat2-cvat-redis-replicas-1                          1/1     Running                      0                 12h
cvat2-cvat-redis-replicas-2                          1/1     Running                      0                 48m
cvat2-cvat-traefik-68448f988-wdvnb                   1/1     Running                      0                 13h
```

but the pg is not starting. 
The reason is that the secret name is incorrectly created:

```
      PGDATA:                               /bitnami/postgresql/data
      POSTGRES_POSTGRES_PASSWORD:           <set to the key 'postgresql-postgres-password' in secret 'cvat-postgres-secret'>  Optional: false
      POSTGRES_USER:                        cvat
      POSTGRES_PASSWORD:                    <set to the key 'postgresql-password' in secret 'cvat-postgres-secret'>  Optional: false
      POSTGRES_DB:                          cvat
```

```
kubectl get secrets -n cvat2
NAME                             TYPE                                  DATA   AGE
cvat2-cvat-postgres-secret       generic                               6      13h <--------
cvat2-cvat-redis-token-djwgz     kubernetes.io/service-account-token   3      13h
cvat2-cvat-traefik-token-pdwrr   kubernetes.io/service-account-token   3      13h
default-token-v8bfm              kubernetes.io/service-account-token   3      13h
```

***What is the desired behavour?***

To have an option to install cvat with any custom release name.
