### ISSUE TITLE
Can view mounted files but cant load

### ISSUE THREAD

**Issue by Harsturomai** [opencv/cvat#5272]
### My actions before raising this issue
- [x ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ x] Searched [past issues](/issues)

### Expected Behaviour
Mounted share by following docs. Can view the list of files in the UI, and would expect to be able to create a task using a selection from this list.

Despite being able to view the files, I get the following error when trying to create a task from them:

```
Could not create the task on the server. FileNotFoundError: [Errno 2] No such file or directory: '/home/django/share/image.tiff.
```

### Your Environment
Using Ubuntu 20.04.5.

`docker-compose.yml`

```
...
volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_share:
    driver_opts:
      type: none
      device: /my folder
      o: bind

cvat_server:
    ...
    volumes:
      - cvat_data:/home/django/data
      - cvat_keys:/home/django/keys
      - cvat_logs:/home/django/logs
      - cvat_share:/home/django/share:ro
```

Very odd behaviour. CVAT server can obviously read the files and access the share, but I get a file not found error when trying to create the task after selecting said files...
