### ISSUE TITLE
Release GPU memory during idle auto-annotation models

### ISSUE THREAD

**Issue by Tpoc311** [opencv/cvat#5347]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Hi, everyone!
I have successfully deployed custom auto-annotation models. Each model runs in its own docker container.
But I noticed that the container always takes GPU memory even auto-annotation is not running.
That is a problem because I use this GPU also for models training.

So the question is: how to make the model occupy the GPU only during auto anntation? 
To make it to release GPU during idle so I could use the GPU during idle time to train models.

### Context

I've tried to release GPU memory by running:
```
del model
torch.cuda.empty_cache()
```

And it would work cause `torch.cuda.memory_allocated()` returns 0, but `nvidia-smi` command shows that memory is still allocated for the process:

![изображение](https://user-images.githubusercontent.com/38178648/203562833-4635cf81-f2b9-4abd-bf82-a0b43f2d78b7.png)

As I discovered, the memory is allocated for CUDA context. OK, next try to resolve.

It is possible to close the context by running:
```
cuda.select_device(your_gpu_id)
cuda.close()
```

It works and `nvidia-smi` shows that GPU memory was freed:

![изображение](https://user-images.githubusercontent.com/38178648/203563031-e791caa2-9ab5-4be4-bd09-ef58e61710b4.png)

But when I try to load and run the model again i get an error:

![изображение](https://user-images.githubusercontent.com/38178648/203562500-8b8d9b0e-7b26-4f8f-99db-95ce5e0d9a17.png)

### Your Environment

function.yml:
```
metadata:
    name: pth.custom_model.centernet.ccl
    namespace: cvat
    annotations:
        name: CenterNet CCL
        type: detector
        framework: pytorch
        spec: |
            [
              { "id": 0, "name": "class1" },
              { "id": 1, "name": "class2" },
              { "id": 2, "name": "class3" }
            ]

spec:
    description: Custom model CenterNet for CCL project
    runtime: 'python:3.6'
    handler: main:handler
    eventTimeout: 30s
    env:
        - name: NUCLIO_PYTHON_EXE_PATH
          value: /opt/nuclio/common/openvino/python3

    build:
        image: cvat/pth.custom_model.centernet.ccl
        baseImage: ccl_auto_annotation:v1 # Created by myself image

    triggers:
        myHttpTrigger:
            maxWorkers: 1
            kind: 'http'
            workerAvailabilityTimeoutMilliseconds: 10000
            attributes:
                maxRequestBodySize: 33554432 # 32MB

    platform:
        attributes:
            restartPolicy:
                name: always
                maximumRetryCount: 3
            mountMode: volume
```

BaseImage dockerfile:
```
FROM nvidia/cuda:11.6.0-cudnn8-devel-ubuntu18.04

USER root

# Install Python3 && pip
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y --no-install-recommends sudo vim openssh-server git g++ wget make python3 python3-pip \
    python3-dev libprotobuf-dev protobuf-compiler libopencv-dev libgoogle-glog-dev libboost-all-dev \
    libhdf5-dev libatlas-base-dev ffmpeg libsm6 libxext6 \
    && ln -sf python3 /usr/bin/python \
    && ln -sf pip3 /usr/bin/pip \
    && ln -s /usr/bin/python3 /usr/local/bin/python \
    && pip3 install --upgrade pip \
    && pip3 install setuptools==59.6.0

# Copy and install requirements
COPY centernet/requirements.basic_ml.txt /opt/nuclio/requirements.basic_ml.txt
COPY centernet/requirements.txt /opt/nuclio/requirements.txt
RUN pip3 install -r /opt/nuclio/requirements.txt

# Copy CenterNet files and compile NMS
COPY centernet/comp_vision /opt/nuclio/comp_vision
RUN cd /opt/nuclio/comp_vision/src/centernet_libs/external && make

# Copy project files
COPY ccl /opt/nuclio

ENV PYTHONPATH "${PYTHONPATH}:/opt/nuclio/comp_vision/"
ENV PYTHONPATH "${PYTHONPATH}:/opt/nuclio/"
```

main.py:
```
import base64
import io
import json

import yaml
from PIL import Image

from config import YAML_PATH
from model_handler import ModelHandler


def init_context(context):
    context.logger.info("Init context...  0%")
    with open(YAML_PATH, 'rb') as function_file:
        functionconfig = yaml.safe_load(function_file)
    labels_spec = functionconfig['metadata']['annotations']['spec']
    labels = {item['id']: item['name'] for item in json.loads(labels_spec)}
    model = ModelHandler(labels)
    context.user_data.model = model
    context.logger.info("Init context...100%")


def handler(context, event):
    context.logger.info("Run CenterNet model")
    data = event.body
    buf = io.BytesIO(base64.b64decode(data["image"].encode('utf-8')))
    image = Image.open(buf)
    results = context.user_data.model.infer(image)
    print(results)
    return context.Response(body=json.dumps(results), headers={}, content_type='application/json', status_code=200)

```

model_handler.py:
```
import os

import numpy as np
from src.centernet_libs.detectors.ctdet import CtdetDetector
from src.centernet_libs.opts import Opts
from src.one_stream_handler import OneStreamHandler
from config import MODEL_PATH, ARCH


class ModelHandler:
    def __init__(self, labels):
        a = ['ctdet',
             '--load_model', MODEL_PATH,
             '--arch', ARCH,
             '--nms'
             ]
        opt = Opts().init(args=a)
        self.one_stream_handler = OneStreamHandler()
        os.environ['CUDA_VISIBLE_DEVICES'] = opt.gpus_str
        opt.debug = max(opt.debug, 1)
        self.model = CtdetDetector(opt)
        self.model.pause = False
        self.labels = labels

    def infer(self, image):
        np_image = np.array(image)
        _, ret = self.model.run(np_image)
        prediction = self.one_stream_handler.post_process_dets(np_image, ret['results'])

        results = []
        for obj in prediction:
            results.append({
                "confidence": str(obj.get_score()),
                "label": obj.get_type().name,
                "points": obj.get_bounding_box(),
                "type": "rectangle",
            })

        return results
```

- Docker version 20.10.14, build a224086
- Kubernetes v1.19.0
