### ISSUE TITLE
failed to mount local volume，no such file or directory

### ISSUE THREAD

**Issue by LlemoningL** [opencv/cvat#5433]
### My actions before raising this issue
- [√] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [√] Searched [past issues](/issues)

### Expected Behaviour
mount local volume to cvat_share

### Current Behaviour
I followd link "https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path" suggetions, set "docker-compose.override.yml" with my local volume:
version: '3.3'

services:
  cvat_server:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_default:
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /home/ztx/lj/cvat/cvat/DockCvatShare
      o: bind
the run "docker-compose uo -d" or "docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d --build cvat_server", but both of them show the same error:
ERROR: for cvat_server  Cannot create container for service cvat_server: failed to mount local volume: mount /home/ztx/lj/cvat/cvat/DockCvatShare:/var/lib/docker/volumes/cvat_cvat_share/_data, flags: 0x1000: no such file or directory

ERROR: for cvat_server  Cannot create container for service cvat_server: failed to mount local volume: mount /home/ztx/lj/cvat/cvat/DockCvatShare:/var/lib/docker/volumes/cvat_cvat_share/_data, flags: 0x1000: no such file or directory

![image](https://user-images.githubusercontent.com/87298601/206351105-d9190a68-9242-4035-b37f-2facfd5d4799.png)

### the directory dose exist in my local volume.
how can I solve this problem?

### Your Environment

-Git hash commit (git log -1):03dd995bc304277cc9bfba30d5158d364360100a
-Docker version docker version (e.g. Docker 17.0.05):20.10.21
-Operating System and version (e.g. Linux, Windows, MacOS):Ubuntu 20.04.4 LTS

**Comment by nmanovic** [comment]
@LlemoningL , please check that `/home/ztx/lj/cvat/cvat/DockCvatShare` exists. I will close the question. Please ask in our public channels if you have other questions: https://github.com/opencv/cvat#contact-us

**Comment by lucidBrot** [comment]
I just had the same issue on Windows 10, WSL2, and figured it out thanks to https://forums.docker.com/t/problem-with-named-volume-in-docker-compose/98299

This "works" but is not in the docker compose and thus not working with the other containers:
```bash
docker run --volume /mnt/c/Users/Eric/Documents/recordings/:/home/django/share --entrypoint /bin/bash -it bdea9d7b7523
```

This `docker-compose.override.yml` does not work:
```
services:
  cvat_server:
    volumes:
      - cvat_share:/home/django/share
  cvat_worker_import:
    volumes:
      - cvat_share:/home/django/share
  cvat_worker_export:
    volumes:
      - cvat_share:/home/django/share
  cvat_worker_annotation:
    volumes:
      - cvat_share:/home/django/share

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: "/mnt/c/Users/MyName/Documents/recordings"
      o: bind
```

This `docker-compose.override.yml` **works**:
```
services:
  cvat_server:
    volumes:
      - cvat_share:/home/django/share
  cvat_worker_import:
    volumes:
      - cvat_share:/home/django/share
  cvat_worker_export:
    volumes:
      - cvat_share:/home/django/share
  cvat_worker_annotation:
    volumes:
      - cvat_share:/home/django/share

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: "/mnt/c/Users/MyName/Documents/recordings"
      o: bind
    driver: local
```

The difference is only the last line, which should be the default anyway, but it gets rid of the error message below.
```
Error response from daemon: failed to mount local volume: mount /mnt/c/Users/MyName/Documents/recordings:/var/lib/docker/volumes/cvat_cvat_share/_data, flags: 0x1000: no such file or directory
```
