### ISSUE TITLE
missing part of Social auth configuration at production environment

### ISSUE THREAD

**Issue by kbc8894** [opencv/cvat#5526]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

The variables `SOCIAL_APP_LOGIN_REDIRECT_URL`, `GOOGLE_CALLBACK_URL`, `GITHUB_CALLBACK_URL` should be changeable

### Current Behaviour

It doesn't change.
so, I hard coded `GOOGLE_CALLBACK_URL`, `SOCIAL_APP_LOGIN_REDIRECT_URL` variable at [cvat/settings/base.py](https://github.com/opencv/cvat/blob/v2.3.0/cvat/settings/base.py)
and build
```bash
docker build -t cvat/server:v2.3.0 .
```
It works.

### Possible Solution

some code added at [cvat/settings/production.py](https://github.com/opencv/cvat/blob/v2.3.0/cvat/settings/production.py) like [cvat/settings/development.py](https://github.com/opencv/cvat/blob/v2.3.0/cvat/settings/development.py) and guide

### Steps to Reproduce (for bugs)

1. behind reverse proxy (ex. nginx proxy manager) for ssl.
2. Create `docker-compose.override.yml` with the following code
```yaml
version: '3.3'
services:
  cvat_server:
    environment:
      USE_ALLAUTH_SOCIAL_ACCOUNTS: 'True'
      SOCIAL_AUTH_GOOGLE_CLIENT_ID: '<YOUR_GOOGLE_CLIENT_ID>'
      SOCIAL_AUTH_GOOGLE_CLIENT_SECRET: '<YOUR_GOOGLE_CLIENT_SECRET>'
      GOOGLE_CALLBACK_URL: https://cvat.example.com/api/auth/google/login/callback/
      SOCIAL_APP_LOGIN_REDIRECT_URL: 'https://cvat.example.com/auth/login-with-social-app'
```
4. In a terminal, run the following command
```bash
CVAT_HOST=cvat.example.com docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d
```

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>
