### ISSUE TITLE
CVAT installed on a server - Could not fetch models meta information

### ISSUE THREAD

**Issue by DP1701** [opencv/cvat#5594]
Hello all,

we have a speed problem with CVAT when we have installed it on a server. 

The following constellation:
- Docker is on a Linux server (Docker 20.10.21, Ubuntu 20.04)
- The virtual machine is assigned 8 cores and 32 GB Ram
- Everything is installed on an SSD
- Images (CVAT data files) are stored on a NAS with a 1 GBit connection

Login works fine but it takes a long time to load the projects or tasks. This message also appears frequently:

**Could not fetch models meta information - Open the Browser Console to get details**

Console output:

<img width="541" alt="Bildschirmfoto 2023-01-12 um 15 06 37" src="https://user-images.githubusercontent.com/68444979/212823760-fe7292aa-7d4f-4777-9886-d3abe1bcf67a.png">

Does anyone have a tip on what the problem might be, or instructions on how best to install CVAT on a server?

**Comment by azhavoro** [comment]
please attach logs from cvat_server container: `docker logs cvat_server > cvat.log`

**Comment by DP1701** [comment]
Here are the logs:

[Uploading cvat_logs.txt…]()

I had the message today 18.01. at 9:15 a.m. and yesterday at 12 p.m.

**Comment by DP1701** [comment]
Here are the logs:

[cvat_logs.txt](https://github.com/opencv/cvat/files/10444618/cvat_logs.txt)

I had the message today 18.01. at 9:15 a.m. and yesterday at 12 p.m.

**Comment by DP1701** [comment]
@azhavoro Is there anything noted in the log file that indicates the problem?

**Comment by DP1701** [comment]
Maybe for info, which CVAT version we have installed on the server.
<img width="785" alt="Version" src="https://user-images.githubusercontent.com/68444979/214046665-5029ca49-bafa-4ff2-960f-fc5c6bcc4e95.png">

**Comment by azhavoro** [comment]
Hi, sorry for the late reply

This is the same issue https://github.com/opencv/cvat/issues/4720

As workarround in you case you can define new volume and just mount to `/home/django/data/cache` path like this:
```yml
services:
  cvat_server:
    volumes:
      - cvat_cache:/home/django/data/cache
  cvat_worker_export:
    volumes:
      - cvat_cache:/home/django/data/cache

  cvat_worker_annotation:
    volumes:
      - cvat_cache:/home/django/data/cache

volumes:
  cvat_cache:
```
