### ISSUE TITLE
"Could not fetch organizations list" error on login

### ISSUE THREAD

**Issue by grzleadams** [opencv/cvat#5607]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

Upon login, any user (LDAP or local/admin) sees the below error.
![image](https://user-images.githubusercontent.com/76970426/213565035-e79f034a-17cf-4ad3-a505-d9198ad210fe.png)
You can create an organization and it appears in `/api/organizations` but does not appear in the organization list in the UI. There doesn't appear to be anything particularly useful in the backend server logs to indicate an issue (see logs below). None of the log entries _seem_ to be related to organizations, and we even use `cvat.backend.server.envs.USE_ALLAUTH_SOCIAL_ACCOUNTS: false` in values.yaml.

### Expected Behaviour
Organizations should appear in the organization list.

### Current Behaviour
The organization list doesn't get populated for any user.

### Possible Solution
No idea... I'm not sure why that TypeError would occur. 

### Steps to Reproduce (for bugs)

1. Deploy in Kubernetes (values.yaml follows):
    ```
    ---
    cvat:
      backend:
        worker:
          export:
            replicas: 2
          import:
            replicas: 2
        server:
          additionalVolumes:
            - name: django-config
              configMap:
                name: django-config
            - name: ldap-ca-crt
              configMap:
                name: ldap-ca-crt
          additionalVolumeMounts:
            - name: django-config
              mountPath: /home/django/settings.py
              subPath: settings.py
            - name: ldap-ca-crt
              mountPath: /tmp/ldap-ca.crt
              subPath: ldap_ca.crt
          envs:
            DJANGO_SETTINGS_MODULE: settings
            ALLOWED_HOSTS: "*"
            DJANGO_MODWSGI_EXTRA_ARGS: ""
            USE_ALLAUTH_SOCIAL_ACCOUNTS: false
        permissionFix:
          enabled: false
      frontend:
        service:
          type: ClusterIP
    ingress:
      enabled: false
    ```
    Our settings.py:
    ```
    # We are overlaying production
    from cvat.settings.production import *
    
    # Custom code below
    import ldap
    from django_auth_ldap.config import LDAPSearch
    from django_auth_ldap.config import NestedActiveDirectoryGroupType
    
    # Notify CVAT that we are using LDAP authentication
    IAM_TYPE = 'LDAP'
    
    # Talking to the LDAP server
    AUTH_LDAP_SERVER_URI = "<redacted>" # IP Addresses also work
    ldap.set_option(ldap.OPT_REFERRALS, 0)
    
    _BASE_DN = "<redacted>"
    
    # Authenticating with the LDAP server
    AUTH_LDAP_BIND_DN = "<redacted>"
    # AUTH_LDAP_BIND_DN = "cvat_bind@ad.example.com"
    AUTH_LDAP_BIND_PASSWORD = "<redacted>"
    
    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        _BASE_DN,
        ldap.SCOPE_SUBTREE,
        "(sAMAccountName=%(user)s)"
    )
    
    AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
        _BASE_DN,
        ldap.SCOPE_SUBTREE,
        "(objectClass=group)"
    )
    
    # Mapping Django field names to Active Directory attributes
    AUTH_LDAP_USER_ATTR_MAP = {
        "user_name": "sAMAccountName",
        "first_name": "givenName",
        "last_name": "sn",
        "email": "mail",
    }
    
    # Group Management
    AUTH_LDAP_GROUP_TYPE = NestedActiveDirectoryGroupType()
    
    # Register Django LDAP backend
    AUTHENTICATION_BACKENDS += ['django_auth_ldap.backend.LDAPBackend']
    
    # Map Active Directory groups to Django/CVAT groups.
    AUTH_LDAP_ADMIN_GROUPS = [
        "<redacted>",
    ]
    AUTH_LDAP_BUSINESS_GROUPS = []
    AUTH_LDAP_WORKER_GROUPS = []
    AUTH_LDAP_USER_GROUPS = []
    
    DJANGO_AUTH_LDAP_GROUPS = {
        "admin": AUTH_LDAP_ADMIN_GROUPS,
        "business": AUTH_LDAP_BUSINESS_GROUPS,
        "user": AUTH_LDAP_USER_GROUPS,
        "worker": AUTH_LDAP_WORKER_GROUPS,
    }
    
    AUTH_LDAP_CONNECTION_OPTIONS = {
        ldap.OPT_X_TLS_CACERTFILE: "/tmp/ldap-ca.crt",
        ldap.OPT_X_TLS_REQUIRE_CERT: ldap.OPT_X_TLS_ALLOW,
        ldap.OPT_X_TLS_NEWCTX: 0
    }
    ```
    Our ingress (we decided not to use the Traefik ingress in the chart since we have cluster-wide ingress-nginx):
    ```
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        field.cattle.io/publicEndpoints: <redacted>
        kubernetes.io/ingress.class: default
      <snip>
    spec:
      rules:
      - host: cvat.<domain>
        http:
          paths:
          - backend:
              service:
                name: cvat-backend-service
                port:
                  number: 8080
            path: /api
            pathType: Prefix
          - backend:
              service:
                name: cvat-backend-service
                port:
                  number: 8080
            path: /admin
            pathType: Prefix
          - backend:
              service:
                name: cvat-backend-service
                port:
                  number: 8080
            path: /static
            pathType: Prefix
          - backend:
              service:
                name: cvat-backend-service
                port:
                  number: 8080
            path: /django-rq
            pathType: Prefix
          - backend:
              service:
                name: cvat-backend-service
                port:
                  number: 8080
            path: /git
            pathType: Prefix
          - backend:
              service:
                name: cvat-backend-service
                port:
                  number: 8080
            path: /opencv
            pathType: Prefix
          - backend:
              service:
                name: cvat-backend-service
                port:
                  number: 8080
            path: /profiler
            pathType: Prefix
          - backend:
              service:
                name: cvat-frontend-service
                port:
                  number: 80
            path: /
            pathType: Prefix
    ```
1. Log in to the application and see the error.

### Context
It makes it difficult for users to interact with organizations, since they don't appear in the list.

### Your Environment

- Git hash commit (`git log -1`): 58b05536f5c1546dfa34d80a911b17e029d33efb
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.21
- Are you using Docker Swarm or Kubernetes? Kubernetes
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 20.04.5 nodes
- Code example or link to GitHub repo or gist to reproduce problem: N/A
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` backend container</summary> 
    2023-01-19 21:17:02,689 DEBG 'runserver' stderr output:
    [Thu Jan 19 21:17:02.689311 2023] [wsgi:error] [pid 194:tid 140605358896896] [remote 10.42.18.171:60542] INFO:cvat.client:{"client_id":938581,"name":"Send user activity","time":"2023-01-19T21:17:02.645000Z","payload":{"working_time":8620},"is_active":true,"username":"admin"}
    
    2023-01-19 21:17:02,818 DEBG 'runserver' stderr output:
    [Thu Jan 19 21:17:02.817966 2023] [wsgi:error] [pid 194:tid 140605358896896] [remote 10.42.18.171:60574] [2023-01-19 21:17:02,817] WARNING django.request: Not Found: /api/user-agreements
    
    2023-01-19 21:17:02,818 DEBG 'runserver' stderr output:
    [Thu Jan 19 21:17:02.818134 2023] [wsgi:error] [pid 194:tid 140605358896896] [remote 10.42.18.171:60574] WARNING:django.request:Not Found: /api/user-agreements
    
    2023-01-19 21:17:02,875 DEBG 'runserver' stderr output:
    [Thu Jan 19 21:17:02.875522 2023] [wsgi:error] [pid 194:tid 140605275002624] [remote 10.42.18.171:60584] [2023-01-19 21:17:02,875] WARNING django.request: Not Found: /api/auth/social/methods
    [Thu Jan 19 21:17:02.875631 2023] [wsgi:error] [pid 194:tid 140605275002624] [remote 10.42.18.171:60584] WARNING:django.request:Not Found: /api/auth/social/methods
    </details>
