### ISSUE TITLE
Can't install 2.3.0 helm because of missing dependency

### ISSUE THREAD

**Issue by gecube** [opencv/cvat#5722]
Hi!

I am using flux for installing your nice CVAT installation.

To do it I am using something like:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: cvat
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: cvat
  namespace: cvat
spec:
  interval: 5m0s
  url: https://github.com/opencv/cvat
  ref:
    tag: v2.3.0
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cvat
  namespace: cvat
spec:
  chart:
    spec:
      chart: ./helm-chart
      sourceRef:
        kind: GitRepository
        name: cvat
  targetNamespace: cvat
  releaseName: cvat
  interval: 5m0s
  timeout: 10m
  values:
    postgresql:  
      global:
        storageClass: gp2
      secret:
        password: ****
        postgres_password: ****
        replication_password: ****
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http01-nginx-issuer
        nginx.ingress.kubernetes.io/proxy-body-size: 1024m
      className: nginx
      hosts:
        - host: *****
          paths:
            - path: /api
              pathType: "Prefix"
              service:
                name: backend-service
                port: 8080
            - path: /admin
              pathType: "Prefix"
              service:
                name: backend-service
                port: 8080
            - path: /static
              pathType: "Prefix"
              service:
                name: backend-service
                port: 8080
            - path: /django-rq
              pathType: "Prefix"
              service:
                name: backend-service
                port: 8080
            - path: /git
              pathType: "Prefix"
              service:
                name: backend-service
                port: 8080
            - path: /opencv
              pathType: "Prefix"
              service:
                name: backend-service
                port: 8080
            - path: /profiler
              pathType: "Prefix"
              service:
                name: backend-service
                port: 8080
            - path : /
              pathType: "Prefix"
              service:
                name: frontend-service
                port: 80
      tls:
        - hosts:
          - ****
          secretName: ingress-tls-cvat
```

It is perfectly the same as to use helm install directly.
And I am gotting the error:

```
cvat             	helmchart/cvat-cvat                        	        	False    	False	dependency build error: failed to add remote dependency 'postgresql': failed to get chart 'postgresql' version '10.16.*' from 'https://charts.bitnami.com/bitnami': no 'postgresql' chart with version matching '10.16.*' found
```

I begin to investigate the issue.
And I wonder very much as there is no such a chart in official bitnami repo!

```bash
$ helm search repo bitnami/postgresql  --versions
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION                                       
bitnami/postgresql   	12.2.0       	15.2.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.15      	15.2.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.14      	15.1.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.13      	15.1.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.12      	15.1.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.11      	15.1.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.10      	15.1.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.9       	15.1.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.8       	15.1.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.7       	15.1.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.6       	15.1.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.5       	15.1.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.4       	15.1.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.3       	15.1.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.2       	15.1.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.1       	15.0.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.1.0       	15.0.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.0.1       	15.0.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	12.0.0       	15.0.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.9.13      	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.9.12      	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.9.11      	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.9.10      	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.9.9       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.9.8       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.9.7       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.9.6       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.9.5       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.9.2       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.9.1       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.9.0       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.8.2       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.8.1       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.8.0       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.7.6       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.7.5       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.7.4       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.7.3       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.7.2       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.7.1       	14.5.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.7.0       	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.26      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.25      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.24      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.23      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.22      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.21      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.20      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.19      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.18      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.17      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.16      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.15      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.14      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.13      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.12      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.11      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.10      	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.9       	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.8       	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.7       	14.4.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.6       	14.3.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.5       	14.3.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.4       	14.3.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.3       	14.3.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql   	11.6.2       	14.3.0     	PostgreSQL (Postgres) is an open source object-...
bitnami/postgresql-ha	11.1.2       	15.2.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	11.1.1       	15.1.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	11.1.0       	15.1.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	11.0.1       	15.1.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	11.0.0       	15.1.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	10.0.9       	15.1.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	10.0.8       	15.1.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	10.0.7       	15.1.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	10.0.6       	15.1.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	10.0.5       	15.1.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	10.0.4       	15.1.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	10.0.3       	15.1.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	10.0.2       	15.0.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	10.0.1       	15.0.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	10.0.0       	15.0.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.4.11       	14.5.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.4.10       	14.5.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.4.9        	14.5.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.4.6        	14.5.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.4.5        	14.5.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.4.4        	14.5.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.4.3        	14.5.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.4.2        	14.5.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.4.1        	14.5.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.4.0        	14.5.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.3.8        	14.5.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.3.5        	14.5.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.3.4        	14.5.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.3.3        	14.5.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.3.2        	14.4.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.3.0        	14.4.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.2.8        	14.4.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.2.7        	14.4.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.2.6        	14.4.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.2.5        	14.4.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.2.4        	14.4.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.2.3        	14.4.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.2.2        	14.4.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.2.1        	14.4.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.2.0        	14.4.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.1.9        	14.4.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.1.8        	14.4.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.1.7        	14.4.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.1.6        	14.4.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.1.5        	14.3.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.1.4        	14.3.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.1.2        	14.3.0     	This PostgreSQL cluster solution includes the P...
bitnami/postgresql-ha	9.1.1        	14.3.0     	This PostgreSQL cluster solution includes the P...
```

This is the whole list of available postgres and postgres-ha charts by Bitnami. Any ideas?
I may guess that bitnami removed the old charts as discontinued...

### The expected behaviour:

I can install CVAT helm chart in one-go without any errors and without any necessity to use external postgres.
