### ISSUE TITLE
Cannot export or backup task - shared_path in Windows

### ISSUE THREAD

**Issue by arman258** [opencv/cvat#5840]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. Mount the shared path using https://github.com/opencv/cvat/issues/1472#issuecomment-1399890382 
`docker volume create --name cvat_cvat_share --opt type=none --opt device=C:\Users\Arman\Downloads\Compressed --opt o=bind
`
1. Import the images, create a task, and start annotating
1. Export or backup task with images included gives the error: 
`Error: Request failed with status code 500. "datumaro.components.errors.ItemExportError: Failed to export item ('spk_airport/RW12/221020_134008_012_FH_frame_2361', 'default')\n".`

### Expected Behaviour

Although the images are loaded correctly, when exporting, CVAT is looking in `'/home/django/share/[image_path]'\n".` which is not the correct directory C:\Users\Arman\Downloads\Compressed\[image_path]

### Your Environment

- Git hash commit (`git log -1`):  29be40dda6cee64bd662f27b2589223e220470bf
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.22, build 3a2c30b
- Operating System and version (e.g. Linux, Windows, MacOS): Windows WSL2 backend
- Other diagnostic information / logs:  https://gist.github.com/arman258/ba4ab56f2bf672e98260528ccbec79d5

**Comment by arman258** [comment]
Okay, I figured it out. 

For anyone on windows, Use #1472 and make sure to use PowerShell when entering the windows path, e.g.,
`docker volume create --name cvat_cvat_share --opt type=none --opt device=**dir_path** --opt o=bind`

Create your docker-compose.override.yml as:

```
services:
  cvat_server:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_import:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_export:
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
```
Adding the cvat_worker_export did the trick.
