### ISSUE TITLE
user log error and make new task error 

### ISSUE THREAD

**Issue by 315386775** [opencv/cvat#5849]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

i get the log error infomation now. but everything is ok yesterday.

## User log error 

![20230314095459](https://user-images.githubusercontent.com/12441747/224872748-8bbf0b8a-9767-47f9-8322-551e5ecfa892.png)

## New task pre-label error

![20230314102331](https://user-images.githubusercontent.com/12441747/224876605-8c664ff9-0e7c-47f1-9de3-cc323276c496.png)
![20230314102345](https://user-images.githubusercontent.com/12441747/224876610-3899cdae-a3a5-4e48-aad4-5dfb20b99d22.png)

## Cvat server server.txt

```
2023-03-14 01:44:34,197 DEBG 'runserver' stderr output:
[Tue Mar 14 01:44:34.197364 2023] [wsgi:error] [pid 322:tid 140320213747456] ERROR:LogProcessingWorker:Log processing error (queue size: 217932): database disk image is malformed
[Tue Mar 14 01:44:34.197401 2023] [wsgi:error] [pid 322:tid 140320213747456] Traceback (most recent call last):
[Tue Mar 14 01:44:34.197404 2023] [wsgi:error] [pid 322:tid 140320213747456]   File "/opt/venv/lib/python3.8/site-packages/logstash_async/worker.py", line 145, in _process_event
[Tue Mar 14 01:44:34.197407 2023] [wsgi:error] [pid 322:tid 140320213747456]     self._write_event_to_database()
[Tue Mar 14 01:44:34.197409 2023] [wsgi:error] [pid 322:tid 140320213747456]   File "/opt/venv/lib/python3.8/site-packages/logstash_async/worker.py", line 195, in _write_event_to_database
[Tue Mar 14 01:44:34.197412 2023] [wsgi:error] [pid 322:tid 140320213747456]     self._database.add_event(self._event)
[Tue Mar 14 01:44:34.197414 2023] [wsgi:error] [pid 322:tid 140320213747456]   File "/opt/venv/lib/python3.8/site-packages/logstash_async/database.py", line 92, in add_event
[Tue Mar 14 01:44:34.197417 2023] [wsgi:error] [pid 322:tid 140320213747456]     connection.execute(query, (event, False))
[Tue Mar 14 01:44:34.197419 2023] [wsgi:error] [pid 322:tid 140320213747456] sqlite3.DatabaseError: database disk image is malformed
```

[server.txt](https://github.com/opencv/cvat/files/10963590/server.txt)

i have checked some infomation about sqlite3.DatabaseError: database disk image is malformed, but not get the soloution.

**Comment by 315386775** [comment]
where is database location. i checked the following location but get nothing.

```
services:
  cvat_db:
    container_name: cvat_db
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db:/var/lib/postgresql/data
    networks:
      - cvat
```
