### ISSUE TITLE
XHR timeout too low for endpoint /api/server/health

### ISSUE THREAD

**Issue by MidnessX** [opencv/cvat#6105]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Context
I've deployed CVAT on a Kubernetes cluster using custom manifests.
Persistent volumes are on a NFS share so speed is not exactly great, but should be sufficient.

### Current Behaviour
The CVAT UI sends an XHR to the ``/api/server/health`` endpoint using a timeout value of 5 seconds.
This request times out due to the server taking slightly more than 5 seconds to respond and this leads to the UI displaying the "Cannot connect to the server" popup.

Manually visiting the endpoint tells me every service is up and working, as can be seen in the screenshot below.
![Screenshot from 2023-05-04 16-00-08](https://user-images.githubusercontent.com/72510075/236230604-f0d46e3b-25bd-42d0-801a-7a81a19cb5f0.png)

I do not know what ``Cache backend: media`` is, but I suspect its check taking so long to be caused by the poor NFS share performance.

Setting a breakpoint and manually increasing the XHR timeout value to 10 seconds solves everything and CVAT works as intended.

### Expected Behaviour
I manage to get past health checks and to the login page.

### Possible Solution
The XHR timeout appears to be set [here](https://github.com/opencv/cvat/blob/5399f6e189c547dd7948bfac2b4ff61f5b907848/cvat-core/src/api.ts#L107), so increasing the value of ``requestTimeout`` should fix the problem.

Alternatively, find a way to reduce the time the ``Cache backend: media`` check takes.

### Your Environment

- CVAT release ``v2.4.3``
- Kubernetes ``1.26.3``

**Comment by azhavoro** [comment]
Please do not store cvat cache (/home/django/data/cache) on NFS storage, media-cache is a [diskcache](https://github.com/grantjenks/python-diskcache) instance that uses sqlite inside. Sqlite will not work on NFS storage. You can mount local storage via additionalVolumes to avoid problems with sqlite.

**Comment by TheRealRolandDeschain** [comment]
Having the exact same problem, I would be interested in a valid fix as well!

**Comment by TheRealRolandDeschain** [comment]
> Thanks for the heads up!
> 
> I've created an `emptyDir` volume mounted into `/home/django/data/cache` for each pod: now the `Cache backend: media` check takes less than 2 ms.
> 
> I believe it's ok to have different caches for each `cvat/server` container (i.e. cvat-server, cvat-utils, cvat-worker-import, etc.). Can you confirm this? Otherwise I will have to move all those containers into a single pod in order for them to share the same `emptyDir` volume.

@MidnessX as far as I can tell  `/home/django/data/´ must be shared between the `cvat/server` images. In my case I have a PVC for all of them pointing to the same folders (same for keys and logs). How did you manage to make `/home/django/data/cache´ local while keeping the parent folder shared?

**Comment by MidnessX** [comment]
Nothing stops you from mounting a volume inside another.

``` yaml
apiVersion: apps/v1
kind: Deployment
# [...]
spec:
    # [...]
    spec:
      containers:
        - name: cvat-server
          # [...]
          volumeMounts:
            - name: cvat-data
              mountPath: /home/django/data
              subPath: data
            - name: cvat-data
              mountPath: /home/django/keys
              subPath: keys
            - name: cvat-data
              mountPath: /home/django/logs
              subPath: logs
           - name: cvat-cache
              mountPath: /home/django/data/cache
      volumes:
        - name: cvat-data
          persistentVolumeClaim:
            claimName: cvat-data-pvc
        - name: cvat-cache
          emptyDir:
            sizeLimit: 5Gi
```
You can simply do as in the above snippet and it will work just fine.

> I believe it's ok to have different caches for each `cvat/server` container (i.e. cvat-server, cvat-utils, cvat-worker-import, etc.). Can you confirm this? Otherwise I will have to move all those containers into a single pod in order for them to share the same `emptyDir` volume.

Answering my own question, the cache volume does not need to be shared between different instances of the server, so a simple ``emptyDir`` on the local node's filesystem is perfectly valid.
