### ISSUE TITLE
Cannot change the mounted path via share path

### ISSUE THREAD

**Issue by Legend94rz** [opencv/cvat#6113]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I have deployed a cvat server on my local machine, and it's share path is configed according the [tutorial](https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path).

Now I want to change the mounted path from `/mnt/share` to another path, e.g. `/mnt/another_share`, so I edit the `docker-compose.override.yml` file, and change the `device` of `cvat_share` to the new path. Then I restart cvat:
```
docker compose down
docker compose -f docker-compose.yml -f docker-compose.override.yml up -d
```
however, when I create new task and select files via `Connected file share`, the content shown is the older path `/mnt/share`.

I have tried update docker image via `docker compose pull` and pull the repo, neither works.

### Steps to Reproduce (for bugs)

1. deploy a cvat, mount a share path
2. change the share path
3. restart server

### Expected Behaviour
the content of mounted folder should be which of the new path.

### Current Behaviour
the content of mounted folder is the old path.

### Your Environment

- Git hash commit (`git log -1`): `commit 255f2d0800ce9fb0879c1b88e9497ea3b3f464d9 `
- Docker version `docker version` (e.g. Docker 17.0.05):`Version:   23.0.1`
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): ubuntu 18.04

**Comment by bsekachev** [comment]
@azhavoro 

Could you please look at the issue?

**Comment by azhavoro** [comment]
@Legend94rz This is not a issue and is not related to CVAT, docker compose will not recreate the volume if you have changed the binded path. First you need to remove the previously created volume `docker volume rm cvat_cvat_data`.

**Comment by Legend94rz** [comment]
@azhavoro Thanks for your help!
But I restart cvat after `docker volume rm cvat_cvat_data`, the share path still is the older one. 
I tried add `--build` param to the start cmd, it doesn't help.

All the images and annotations seems to be deleted, only the job and task links are there. If I click into the job, it tells me `Could not fetch frame data from the server`. 

Did I miss something?

**Comment by Legend94rz** [comment]
any update? 
how about re-open this issue?

**Comment by SaeedAID** [comment]
For everyone's benefit, this solution worked perfectly for me:

- **Ubuntu Version:** 22.04
- **CVAT Server Version:** 2.19.1

In the `docker-compose.yml`, near the end, you will find the following volume declarations:

```
volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_inmem_db:
  cvat_events_db:
  cvat_cache_db:
```
Additionally, I have a shared folder mounted at `/mnt/volume_cvat_01`. To store the CVAT volumes, I created a directory named `cvat_volumes` and set up subdirectories for each volume as follows:

```
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_db
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_data
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_keys
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_logs
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_inmem_db
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_events_db
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_cache_db
```
I then updated the `docker-compose.yml` file with the following volume configurations:

```
volumes:
  cvat_db:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_db
      o: bind
  cvat_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_data
      o: bind
  cvat_keys:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_keys
      o: bind
  cvat_logs:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_logs
      o: bind
  cvat_inmem_db:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_inmem_db
      o: bind
  cvat_events_db:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_events_db
      o: bind
  cvat_cache_db:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_cache_db
      o: bind
```
Finally, set the CVAT host environment variable and start the container:

```
export CVAT_HOST=FQDN_or_YOUR-IP-ADDRESS
docker compose -f docker-compose.yml up -d
```
After that, you can access CVAT using your specified `CVAT_HOST`. Create a project, and navigate to `/mnt/volume_cvat_01/cvat_volumes/cvat_data/projects` to see the created project number.
