### ISSUE TITLE
404 Not found when loading Traefik dashboard

### ISSUE THREAD

**Issue by shan100github** [opencv/cvat#6147]
### My actions before raising this issue
- Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- Referred
- [404 page not found - Docker - CVAT UI](https://github.com/opencv/cvat/issues/6011)
- [404 page not found - Docker - CVAT UI](https://github.com/opencv/cvat/issues/5697)
- [404 page not found - Docker - CVAT UI](https://github.com/opencv/cvat/issues/4322)

### Steps to reproduce
Install CVAT in kubernetes with values.yaml - https://github.com/opencv/cvat/blob/develop/helm-chart/values.yaml#L321-L322
Though successfully installed CVAT upon checking CVAT UI, displays "404 page not found".

### Expected Behaviour
CVAT UI should have been displayed without issues.

### Current Behaviour
Upon CVAT deployment it displays  "404 page not found" error.

### Possible Solution
Added the following in the template and I was able to successfully navigate to CVAT UI.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-traefik-config
  namespace:  {{ .Release.Namespace }}
data:
  traefik.yml: |
    accessLog: {}
    entryPoints:
      web:
        # Listen on port 80 for incoming requests
        address: :80
    providers:
      file:
        filename: /etc/traefik/dynamic.yml
  dynamic.yml: |
    http:
      routers:
        # Define a connection between requests and services
        to-backend:
          rule: "PathPrefix(`/api/`, `/admin/`, `/static/`, `/opencv/`, `/git/`, `/profiler/`, `/django-rq`)"
          # If the rule matches, forward to the whoami service (declared below)
          service: backend
        to-frontend:
          rule: "PathPrefix(`/`)"
          service: frontend
      services:
        # Define how to reach an existing service on our infrastructure
        backend:
          loadBalancer:
            servers:
            - url: http://{{ .Release.Name }}-backend-service:8080
        frontend:
          loadBalancer:
            servers:
            - url: http://{{ .Release.Name }}-frontend-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-traefik
  namespace:  {{ .Release.Namespace }}
  labels:
    app: cvat-traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cvat-traefik
  template:
    metadata:
      labels:
        app: cvat-traefik
    spec:
      containers:
        - name: cvat-traefik
          image: traefik:v2.8
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          volumeMounts:
          - mountPath: /etc/traefik
            name: config
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-traefik-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-traefik-proxy
  namespace:  {{ .Release.Namespace }}
spec:
  selector:
    app: cvat-traefik
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
```

### Your Environment
- Are you using Docker Swarm or Kubernetes? Kuberentes 
- Kubernetes version: v1.24.13+rke2r1
- Operating System and version (e.g. Linux, Windows, MacOS): ubuntu 20.04
