### ISSUE TITLE
How to run 2 CVAT label services on the same computer

### ISSUE THREAD

**Issue by TuanTNG** [opencv/cvat#6196]
Hi CVAT team,

Thank you for your awesome work.
I would like to run 2 CVAT services on the same computer. All the containers start running without any problem.
However, when I open the web UI, let's say I `http://localhost:8080/`, there is nothing appears on the web browser apart from the word `Connecting...` that appears forever. 

Here are my step of doing it:
1. I created 2 different folders, in each folder, I cloned the CVAT code and check out the `release-2.3.0` branch. 
2. I renamed the `docker-compose.yml` in each folder to `docker-compose_8080.yml` and `docker-compose_8081.yml` respectively.
3. In the `docker-compose_8081.yml` file, I changed some variables:
- Change all `cvat` networks to `cvat_8081` networks
- Change all `container_name`. For example, `cvat_db` --> `cvat_db_8081`, `cvat_server` --> `cvat_server_8081`, etc.,
- In the service `traefik`, I change the ports `8080:8080` to `8081:8080` and `8090:8090` to `8091:8090`
Here is the [docker-compose_8080.yml](https://drive.google.com/file/d/1_u8QjOmLkiwNHlGhrpIN-TIxDC5pHfNH/view?usp=share_link) and [docker-compose_8081.yml](https://drive.google.com/file/d/1_D6IJLRKJiyTPEjrjQu9oqK8tUWdpIYy/view?usp=sharing)
5. Keep the file `docker-compose_8080.yml` unchanged.

Start command:
- Start cvat 1: `docker-compose -p cvat_8080 -f docker-compose_8080.yml up -d`
- Start cvat 2: `docker-compose -p cvat_8081 -f docker-compose_8081.yml up -d`

It is worth noting that:
- If I don't start cvat 1 or cvat 2, the other works without any problem. 
- If I remove only one service `cvat_server` in one of the cvat 1 or cvat 2, the other will work perfectly.

What should I do to resolve this problem?

I am looking forward to hearing from you soon.
Thank you in advance.

### My environments:
OS: Ubuntu 18.04.6 LTS
Docker Version: 20.10.17

**Comment by TuanTNG** [comment]
- Here is the output of `docker ps`
![image](https://github.com/opencv/cvat/assets/62212814/182a3b40-bc89-4e8e-b994-b8dda5f63853)

- Here are the logs:
Log of [cvat_8080](https://drive.google.com/file/d/1BQniBLzOgPOFCnkDvYxxK_Nb8Ad8al1O/view?usp=share_link)
Log of [cvat_8081](https://drive.google.com/file/d/1oxZ2Zx2udWwYtvw9idNuOSYrqtJXGdW3/view?usp=share_link)

**Comment by marc31** [comment]
One solution involves deploying CVAT with Docker in rootless mode using two different users and exposing different ports for Traefik. For example, in a docker-compose.override.yml:

```
services:
  traefik:
    ports: !override
      - ${TRAEFIK_PORT:-8080}:8080
      - ${TRAEFIK_DASHBOARD_PORT:-8090}:8090
    volumes:
      # $DOCKER_HOST because we use docker in rootless mode
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - ./components/analytics/grafana_conf.yml:/etc/traefik/rules/grafana_conf.yml:ro
```

Note: !override requires Docker Compose version >= 2.24.4.
