### ISSUE TITLE
Detection error occurred Error: Request failed with status code 502.

### ISSUE THREAD

**Issue by piwawa** [opencv/cvat#6282]
### My actions before raising this issue
`nuctl deploy --project-name cvat \
  --path cvat/serverless/pytorch/ultralytics/yolov5/nuclio  --platform local`

![image](https://github.com/opencv/cvat/assets/46926496/01ef1afd-5b22-4edd-a3cb-810e771374b7)

![image](https://github.com/opencv/cvat/assets/46926496/c06b6517-d337-42f7-8fde-07f3d13b2c51)

I use proxy in `docker-compose.serverless.yml` and `cvat/serverless/pytorch/ultralytics/yolov5/nuclio/function.yaml`, the latter is like this:

```
    directives:
      preCopy:
        - kind: USER
          value: root
        - kind: ENV
          value: https_proxy=http://172.17.0.1:12345/
```

The model is running fine on dashboard:

![image](https://github.com/opencv/cvat/assets/46926496/c8757f1e-36f3-4b70-bd52-224be8d50a8a)

My server is in China, so proxy is inevitable :(
