### ISSUE TITLE
Cannot upload annotation - Content must be served over HTTPS

### ISSUE THREAD

**Issue by hyfung** [opencv/cvat#6309]
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

Same issue in
https://github.com/opencv/cvat/issues/6078

### Steps to Reproduce (for bugs)
- I have an annotation XML that I wish to upload
- Refer to bottom for console logs

### Expected Behaviour
- Expect the upload to be targeting HTTPS instead of HTTP

### Current Behaviour
Mixed Content Error, upload failure

### Possible Solution
CVAT shouldve send PATCH to HTTPS instead of HTTP endpoint

### Your Environment
- Git hash commit (`git log -1`):
```
commit 520d219f3ef1e39b08c8ce0d5da6f4e4f54c2f79 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Andrey Zhavoronkov <andrey@cvat.ai>
Date:   Fri Jun 2 18:40:28 2023 +0300

    Updated CHANGELOG for v2.5.0 (#6234)
```
- Docker version `docker version` (e.g. Docker 17.0.05):
```
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:00 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:51:00 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:

```
Mixed Content: The page at 'https://cvat.XXXXXXXXx.com/tasks?page=1' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://cvat.XXXXXXXXx.com/api/tasks/1234/annotations/1xxxxxxxxxd26'. This content should also be served over HTTPS.
```

```
Access to XMLHttpRequest at 'http://cvat.xxxxxxxxxx.com/api/tasks/1234/annotations/13xxxxxxxxxx5a-85848bd4dd26' from origin 'https://cvat.xxxxxxxxxxxx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

**Comment by azhavoro** [comment]
https://github.com/opencv/cvat/issues/6201#issuecomment-1589544784

**Comment by hyfung** [comment]
Added these lines in the `docker-compose.https.yml` and hope it works

```
services:
  cvat_server:
    labels:
      - traefik.http.routers.cvat.entrypoints=websecure
      - traefik.http.routers.cvat.tls.certresolver=lets-encrypt
      - traefik.http.middlewares.https-redirect.headers.customrequestheaders.X-Forwarded-Proto=https

  cvat_ui:
    labels:
      - traefik.http.routers.cvat-ui.entrypoints=websecure
      - traefik.http.routers.cvat-ui.tls.certresolver=lets-encrypt
      - traefik.http.middlewares.https-redirect.headers.customrequestheaders.X-Forwarded-Proto=https
```
