### ISSUE TITLE
How to install from submodules for serverless

### ISSUE THREAD

**Issue by XinyueZ** [opencv/cvat#6359]
Hey guys,

I want to make a serverless function. The main logic has been encapsulated in a submodule repo, the  `model_handler.py` will just call the content of the submodule.

location:

``` yaml
CVAT
|----serverless
      |------------modules
                     |-------------------some-foo
```

in `function-gpu.yaml ` I added following:

```yaml

        - Kind: ADD
          value: ./modules/some-foo /home/user/
        - kind: RUN
          value: pip3 install /home/user/modules/some-foo 
```

But the `./modules/some-foo` cannot be found  while running `serverless/deploy_gpu.sh` ie.

Any idea, thank you!
