### ISSUE TITLE
Cannot connect mounted share file

### ISSUE THREAD

**Issue by TKluwe** [opencv/cvat#6378]
### My actions before raising this issue
Read https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path
Searched past issues https://github.com/opencv/cvat/issues/2263
Deleted and reinstalled Docker Desktop, Ubuntu and have tried multiple times to run the docker containers once configured to have a  share path and it either doesn't work or hangs on the creation of containers.

I have tried to connect a local drive to CVAT with multiple attempts and have been unable to do so.

### Steps to Reproduce (for bugs)
1. git clone https://github.com/opencv/cvat
2. Create docker-compose.override.yml
3. Create volume using
  linux file system: docker volume create --name cvat_share --opt type=none --opt device=/home/user/cvat_data --opt o=bind
  or
  windows filesystem: docker volume create --name cvat_share --opt type=none --opt device=/mnt/x/cvat_data --opt o=bind
 4. Run docker containers using docker compose up -d and the creation of cvat_vector, cvat_worker_quality_reports, cvat_worker_webhooks, cvat_server, cvat_worker_export, cvat_worker_annotation, cvat_worker_import, cvat_utils hang
 5. If I delete the docker-compose.override.yml and run docker compose up -d CVAT works fine and the creation of the containers do not hang so I do not believe its an issue w/ my system

### Expected Behaviour
Shared drive should be connected.

### Current Behaviour
After creating a docker-compose.override.yml and using docker compose up -d the following containers hang on creation: cvat_vector, cvat_worker_quality_reports, cvat_worker_webhooks, cvat_server, cvat_worker_export, cvat_worker_annotation, cvat_worker_import, cvat_utils

services:
  cvat_server:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_import:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_export:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_annotation:
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /mnt/x/cvat_data(windows filesystem) and also tried /home/user/cvat_data(linux filesystem)
      o: bind

### Context
Would like to be able to use a shared drive to store my images for annotation.

### Your Environment
- Docker version: 24.0.2
- Operating System and version: Windows 11 Pro 22H2 using WSL2 and Ubuntu

**Comment by TKluwe** [comment]
I fixed it these are the steps I took.  I strongly suggest CVAT update their documentation with some more thorough examples on how to link storage because this was annoying to accomplish.

1. Create directory with "sudo mkdir /mnt/cvat_data"
2. Mount the Windows Folder "sudo mount -t drvfs X:/cvat_data /mnt/cvat_data"
3. Create docker-compose.override.yml file as follows:
```
services:
  cvat_server:
    volumes:
      - /mnt/cvat_data:/home/django/share:ro
  cvat_worker_import:
    volumes:
      - /mnt/cvat_data:/home/django/share:ro
  cvat_worker_export:
    volumes:
      - /mnt/cvat_data:/home/django/share:ro
  cvat_worker_annotation:
    volumes:
      - /mnt/cvat_data:/home/django/share:ro

volumes:
  cvat_share:
    driver: local
    driver_opts:
      type: bind
      source: /mnt/cvat_data
      target: /home/django/share
```
4. Run docker compose up -d
5. Create project, create task --> click file share --> files are there.

**Comment by purvaja2001** [comment]
Thanks for the clear explanation.
How the mounted data is visible for you?
Like I have done same process like you mentioned!
But getting Storage Access Fetching Failed error.
Did you ever face it?

**Comment by SaeedAID** [comment]
For everyone's benefit, this solution worked perfectly for me:

- **Ubuntu Version:** 22.04
- **CVAT Server Version:** 2.19.1

In the `docker-compose.yml`, near the end, you will find the following volume declarations:

```
volumes:
  cvat_db:
  cvat_data:
  cvat_keys:
  cvat_logs:
  cvat_inmem_db:
  cvat_events_db:
  cvat_cache_db:
```
Additionally, I have a shared folder mounted at `/mnt/volume_cvat_01`. To store the CVAT volumes, I created a directory named `cvat_volumes` and set up subdirectories for each volume as follows:

```
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_db
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_data
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_keys
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_logs
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_inmem_db
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_events_db
mkdir -p /mnt/volume_cvat_01/cvat_volumes/cvat_cache_db
```
I then updated the `docker-compose.yml` file with the following volume configurations:

```
volumes:
  cvat_db:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_db
      o: bind
  cvat_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_data
      o: bind
  cvat_keys:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_keys
      o: bind
  cvat_logs:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_logs
      o: bind
  cvat_inmem_db:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_inmem_db
      o: bind
  cvat_events_db:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_events_db
      o: bind
  cvat_cache_db:
    driver: local
    driver_opts:
      type: none
      device: /mnt/volume_cvat_01/cvat_volumes/cvat_cache_db
      o: bind
```
Finally, set the CVAT host environment variable and start the container:

```
export CVAT_HOST=FQDN_or_YOUR-IP-ADDRESS
docker compose -f docker-compose.yml up
```
After that, you can access CVAT using your specified `CVAT_HOST`. Create a project, and navigate to `/mnt/volume_cvat_01/cvat_volumes/cvat_data/projects` to see the created project number.
