### ISSUE TITLE
Nuclio deploying sam stuck at building docker image

### ISSUE THREAD

**Issue by cnet-fusionai** [opencv/cvat#6424]
Nuclio deploying sam stuck at building docker image {"image": "cvat.pth.facebookresearch.sam.vit_h:latest"}, have been waiting for more than an hour.
No error or warning.
No log in dashboard.
No clue if there is anything wrong.
Where can I see the building progress or time remaining?

<img width="1196" alt="Snipaste_2023-07-05_16-28-42" src="https://github.com/opencv/cvat/assets/121920745/220024b9-9e55-417e-a517-8bd05880fc7b">
<img width="1820" alt="Snipaste_2023-07-05_15-19-06" src="https://github.com/opencv/cvat/assets/121920745/04c5a67c-7dbb-4b0f-b609-b3e1ca2e030f">

**Comment by bsekachev** [comment]
> for more than an hour

It can take more than one hour. So, just wait.

**Comment by cnet-fusionai** [comment]
> It can take more than one hour. So, just wait.

Thanks.

It upsets me when I can't figure out what's happening, but l'll wait.

Also wondering if there is a way to build the image in advance so as to save some time.

**Comment by cnet-fusionai** [comment]
Add pip source in 'function-gpu.yaml', successfully deployed in minutes.

**Comment by cnet-fusionai** [comment]
> > Add pip source in 'function-gpu.yaml', successfully deployed in minutes.
> 
> could you tell me how to solve this problem ? thanks!

Here is a example: add "-i https://pypi.tuna.tsinghua.edu.cn/simple" after pip instructions in function-gpu.yaml

**Comment by RonaldoSCouto** [comment]
My deploy with an ONNX  custom model, stucked on BUILDING. 
I run a docker ps to see the containers names 
Run a docker logs  <NUCLIO.MYDEPLOY> 
Where I could see that there are problem on ONNX file.
Exception: Cannot load model buraco.onnx: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from XXXXX.onnx failed:Protobuf parsing failed.
25.02.05 21:51:40.532 (W) sor.http.w1.python.logger Failed to read control message {"errRootCause": "EOF"}

**Comment by gohjiayi** [comment]
Hi @cnet-fusionai I've tried your method but the issue still remains for me. I rebuilt cvat and made sure the `serverless/pytorch/facebookresearch/sam/nuclio/function.yaml` file reflected the above changes with the changes below (I am using CPU so this is the right file). Are you able to further advice if these steps were correct?

```yaml
...
      # install basic deps
        - kind: RUN
          value: apt-get update && apt-get -y install curl git python3 python3-pip ffmpeg libsm6 libxext6
      # install sam deps
        - kind: RUN
          value: pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple torch torchvision torchaudio pycocotools matplotlib onnxruntime onnx
      # install sam code
        - kind: RUN
          value: pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple git+https://github.com/facebookresearch/segment-anything.git
      # download sam weights
        - kind: RUN
          value: curl -O https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth
...
```
