### ISSUE TITLE
CVAT_POSTGRES_PORT not used in backend_entrypoint.sh

### ISSUE THREAD

**Issue by codegastudio** [opencv/cvat#6442]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

`backend_entrypoint.sh` not use the `CVAT_POSTGRES_PORT` env var to check the connectivity to a database.
The port is hardcoded to postgres default port `5432`.

So if we want connect a remote db working with another port number, the backend cannot start cause it is stuck by the `wait-for-it.sh` script.

### Steps to Reproduce (for bugs)

Configure an external database in a custom values.yaml
```
postgresql:
  enabled: false
  secret:
    create: false
    name: database
  external:
    host: <remote db host>
    port: <remote db port>
```

### Expected Behaviour
`backend_entrypoint.sh` should use to `CVAT_POSTGRES_PORT` instead of default port `5432`.

### Current Behaviour
Cannot connect to a remote database on an another port than `5432`.

`CVAT_POSTGRES_PORT` value in container is the same than the one define in the values.yaml.

### Possible Solution
Use `CVAT_POSTGRES_PORT` in `backend_entrypoint.sh`
