### ISSUE TITLE
Windows Segment Anything Setup - "json: cannot unmarshal number into Go struct field Meta.metadata.annotations of type string"

### ISSUE THREAD

**Issue by DrewScatterday** [opencv/cvat#6539]
## What is the proper way to deploy serverless functions with Windows, WSL 2, and cvat? 
I initially saw this article https://www.cvat.ai/post/facebook-segment-anything-model-in-cvat and wanted to use Facebooks Segment Anything model in my labeling workflow

## Installing CVAT 
First, I followed this youtube video https://www.youtube.com/watch?v=0GKtQVnzZlk&t and the official install docs https://opencv.github.io/cvat/docs/administration/basics/installation/#windows-10 to successfully install cvat with no issues on windows WSL 2

To summarize that process was:
1. Installing WSL 2 using ```wsl --install``` in powershell 
2. Installing Docker desktop 4.20.1 
3. Enabling the WSL integration 
4. Installing git bash for windows 
5. cloning the cvat repo using git bash 
6. running ```docker compose up -d``` using git bash
7. creating the superuser with the ```manage.py``` script using git bash

I was then able to access cvat at ```localhost:8080``` with no issues

## Importing Nuclio functions
Second, I followed this video https://youtu.be/uKMKM5o5vUw by the same person to successfully deploy the yolo yaml file using the nuclio GUI on windows accessed at ```localhost:8070```

To summarize that process was:
1. ```docker compose down``` in git bash 
2. ```docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d``` in git bash 
3. Then I navigated to ```localhost:8070``` to view the nuclio GUI 
4. I create a new project in the nuclio GUI named ```cvat```, then I go the import menu to import a YAML file for the nuclio function 
5. I import the ```function.yaml``` file inside of ```serverless\pytorch\ultralytics\yolov5\nuclio```
6. I then copy the contents of ```serverless\pytorch\ultralytics\yolov5\nuclio\main.py``` into the "source code" gui window 
7. Then I press deploy and nuclio successfully deploys my yolo function to be used in cvat 

I attempted this exact same process for the function.yaml file for facebook SAM model but I get an error message that I'm not sure where it's coming from but I think it's related to something in the yaml file:
1. I import the ```function.yaml``` file inside of ```\serverless\pytorch\facebookresearch\sam\nuclio```
2. I then copy the contents of ```\serverless\pytorch\facebookresearch\sam\nuclio\main.py``` into the "source code" gui window 
3. Then I press deploy 

The error message I get is ```json: cannot unmarshal number into Go struct field Meta.metadata.annotations of type string```

As a last resort, I've considered trying this youtube video https://www.youtube.com/watch?v=-rDlAJWiJlE. The process looks incredibly tedious (with 40+ steps and hour long video) and I'd probably have to redo my entire cvat installation from scratch. 

What is the easiest way to install this and getting it working? Thanks for any help 

### Your Environment

- Git hash commit (`git log -1`): e5ea2135
- Docker version - Docker desktop 4.20.1 and Docker engine 24.0.2
- Operating System and version (e.g. Linux, Windows, MacOS): Windows 10 Enterprise 10.0.9045 64 bit with wsl 2

**Comment by DrewScatterday** [comment]
Also adding @bswapnil-13 as they are creator of those videos

**Comment by bswapnil-13** [comment]
Hello @DrewScatterday. Sorry for the delay. I'll need to regenerate the issue on my end and for that I'll have to reinstall CVAT on my machine as I am having other issues with the existing CVAT. Hopefully I'll get back to you soon with the solution. Seems like you will need to merge the code from model_handler.py with the main.py code. Please give it a try once.

**Comment by DrewScatterday** [comment]
To further add to this thread I tried to do it in the way that the docs has it written here https://opencv.github.io/cvat/docs/administration/advanced/installation_automatic_annotation/

I installed nuclio amd-64 file for windows and renamed it to ```nuclio.exe``` 

I get met with a the attached screenshot error when trying to run ```deploy_cpu.sh```

**Comment by bswapnil-13** [comment]
Glad to know that you find my videos helpful. Did you install the latest version of CVAT?

**Comment by DrewScatterday** [comment]
My git branch hash is listed above. It was the latest version of cvat a few weeks ago but I may be a few commits behind

**Comment by bswapnil-13** [comment]
@DrewScatterday , you can try another method. Search for Ubuntu in windows' start menu. When you open it, Ubuntu terminal will open. Try running the following piece of commands there:

`cd cvat
docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml down
wget https://github.com/nuclio/nuclio/releases/download/1.8.14/nuctl-1.8.14-linux-amd64
sudo chmod +x nuctl-1.8.14-linux-amd64
sudo ln -sf $(pwd)/nuctl-1.8.14-linux-amd64 /usr/local/bin/nuctl
docker compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d
./serverless/deploy_cpu.sh serverless/pytorch/facebookresearch/sam`    OR
`./serverless/deploy_gpu.sh serverless/pytorch/facebookresearch/sam`

**Comment by bswapnil-13** [comment]
https://youtu.be/JEOFT10kfkY

**Comment by PMazarovich** [comment]
@DrewScatterday, @bswapnil-13 just replace integers to strings when you see them in metadata.
```
metadata:
  name: pth-facebookresearch-sam-vit-h
  namespace: cvat
  annotations:
    name: Segment Anything
    version: 2
    type: interactor
    spec:
    framework: pytorch
    min_pos_points: 1
    min_neg_points: 0
    animated_gif: https://raw.githubusercontent.com/opencv/cvat/develop/site/content/en/images/hrnet_example.gif
    help_message: The interactor allows to get a mask of an object using at least one positive, and any negative points inside it
```

Transform to 
```

metadata:
  name: pth-facebookresearch-sam-vit-h
  namespace: cvat
  annotations:
    name: Segment Anything
    version: "2"
    type: interactor
    spec:
    framework: pytorch
    min_pos_points: "1"
    min_neg_points: "0"
    animated_gif: https://raw.githubusercontent.com/opencv/cvat/develop/site/content/en/images/hrnet_example.gif
    help_message: The interactor allows to get a mask of an object using at least one positive, and any negative points inside i
```

That's it
