### ISSUE TITLE
deploying CVAT on AKS and SAM

### ISSUE THREAD

**Issue by AsafPe** [opencv/cvat#6682]
### My actions before raising this issue
- [V] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation) 
- [V] Searched [past issues](/issues)

Hi, we are trying to deploy the CVAT environment in AKS, the deployment went fine but the SAM function failed no matter what we tried.

we are using AKS, docker hub (private project), nuctl
we are running the cpu version of SAM, using deploy_cpu.sh with some changes for our environment (detailed below)

### Steps to Reproduce (for bugs)

1.  clone cvat project
1. deploy using https://opencv.github.io/cvat/docs/administration/advanced/k8s_deployment_with_helm/
1. we used override values.yaml 
1. run sudo ./~/cvat/servless/deploy_cpu.sh 

### Expected Behaviour
running CVAT environment on AKS with SAM function

### Current Behaviour
CVAT environment on AKS with SAM function not works

### Your Environment

- Git hash commit (`git log -1`): develop latest
- Docker version `docker version` (e.g. Docker 17.0.05): 
```
Client: Docker Engine - Community
 Version:      24.0.5
 API version:    1.43
 Go version:    go1.20.6
 Git commit:    ced0996
 Built:       Fri Jul 21 20:35:18 2023
 OS/Arch:      linux/amd64
 Context:      default
Server: Docker Engine - Community
 Engine:
 Version:     24.0.5
 API version:   1.43 (minimum version 1.12)
 Go version:    go1.20.6
 Git commit:    a61e2b4
 Built:      Fri Jul 21 20:35:18 2023
 OS/Arch:     linux/amd64
 Experimental:   false
 containerd:
 Version:     1.6.22
 GitCommit:    8165feabfdfe38c65b599c4993d227328c231fca
 runc:
 Version:     1.1.8
 GitCommit:    v1.1.8-0-g82f18fe
 docker-init:
 Version:     0.19.0
 GitCommit:    de40ad0
- Are you using Docker Swarm or Kubernetes? Kubernetes
- Operating System and version (e.g. Linux, Windows, MacOS): Linux Ubuntu 22 (client)
```
- Code example or link to GitHub repo or gist to reproduce problem:
function.yaml:
```
#!/bin/bash
# Sample commands to deploy nuclio functions on CPU
​
set -eu
​
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
FUNCTIONS_DIR=${1:-$SCRIPT_DIR}
​
export DOCKER_BUILDKIT=1
​
#sudo docker build -t cvat.openvino.base "$SCRIPT_DIR/openvino/base"
​
nuctl create project cvat --platform kube --namespace cvat
​
shopt -s globstar
​
for func_config in "$FUNCTIONS_DIR"/**/function.yaml
do
    func_root="$(dirname "$func_config")"
    func_rel_path="$(realpath --relative-to="$SCRIPT_DIR" "$(dirname "$func_root")")"
​
    if [ -f "$func_root/Dockerfile" ]; then
        sudo docker build -t "cvat.${func_rel_path//\//.}.base" "$func_root"
    fi
​
    echo "Deploying $func_rel_path function..."
    nuctl deploy --project-name cvat --path "$func_root" \
        --file "$func_config" --platform kube --namespace cvat
done
```
​deploy_cpu.sh:
```
# Copyright (C) 2023 CVAT.ai Corporation
#
# SPDX-License-Identifier: MIT
​
metadata:
  name: pth-facebookresearch-sam-vit-h
  namespace: cvat2
  annotations:
    name: Segment Anything
    version: 2
    type: interactor
    spec:
    framework: pytorch
    min_pos_points: 1
    min_neg_points: 0
    animated_gif: https://raw.githubusercontent.com/opencv/cvat/develop/site/content/en/images/hrnet_example.gif
    help_message: The interactor allows to get a mask of an object using at least one positive, and any negative points inside it
​
spec:
  description: Interactive object segmentation with Segment-Anything
  runtime: 'python:3.8'
  handler: main:handler
  eventTimeout: 30s
  env:
    - name: PYTHONPATH
      value: /opt/nuclio/sam
​
  build:
    image: <our_project>/cvat-functions
    baseImage: ubuntu:22.04
    directives:
      preCopy:
      # disable interactive frontend
        - kind: ENV
          value: DEBIAN_FRONTEND=noninteractive
      # set workdir
        - kind: WORKDIR
          value: /opt/nuclio/sam
      # install basic deps
        - kind: RUN
          value: apt-get update && apt-get -y install curl git python3 python3-pip ffmpeg libsm6 libxext6
      # install sam deps
        - kind: RUN
          value: pip3 install torch torchvision torchaudio opencv-python pycocotools matplotlib onnxruntime onnx
      # install sam code
        - kind: RUN
          value: pip3 install git+https://github.com/facebookresearch/segment-anything.git
      # download sam weights
        - kind: RUN
          value: curl -O https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth
      # map pip3 and python3 to pip and python
        - kind: RUN
          value: ln -s /usr/bin/pip3 /usr/local/bin/pip && ln -s /usr/bin/python3 /usr/bin/python
  triggers:
    myHttpTrigger:
      maxWorkers: 1
      kind: 'http'
      workerAvailabilityTimeoutMilliseconds: 10000
      attributes:
        maxRequestBodySize: 33554432 # 32MB
​
  platform:
    attributes:
      restartPolicy:
        name: always
        maximumRetryCount: 3
      mountMode: volume
​
nuctl get function --platform kube -n cvat
```

- Other diagnostic information / logs:
```
23.08.14 14:29:04.730                     nuctl (I) Project created {"Name": "cvat", "Namespace": "cvat"}
Deploying pytorch/facebookresearch/sam function...
23.08.14 14:29:05.324                     nuctl (I) Deploying function {"name": "pth-facebookresearch-sam-vit-h"}
23.08.14 14:29:05.333                     nuctl (I) Building {"builderKind": "docker", "versionInfo": "Label: 1.11.24, Git commit: f2a3900d23b92fd3639dc9cb765044ef53a4fb2b, OS: linux, Arch: amd64, Go version: go1.19.10", "name": "pth-facebookresearch-sam-vit-h"}
23.08.14 14:29:05.389                     nuctl (I) Staging files and preparing base images
23.08.14 14:29:05.390                     nuctl (I) Building processor image {"registryURL": "", "taggedImageName": “<out_project>/cvat-functions:latest"}
23.08.14 14:29:05.390     nuctl.platform.docker (I) Pulling image {"imageName": "quay.io/nuclio/handler-builder-python-onbuild:1.11.24-amd64"}
23.08.14 14:29:08.349            nuctl.platform (I) Building docker image {"image": "<out_project>/cvat-functions:latest"}
23.08.14 14:29:09.498            nuctl.platform (I) Pushing docker image into registry {"image": "<out_project>/cvat-functions:latest", "registry": ""}
23.08.14 14:29:09.498            nuctl.platform (I) Docker image was successfully built and pushed into docker registry {"image": "<out_project>/cvat-functions:latest"}
23.08.14 14:29:09.498                     nuctl (I) Build complete {"image": "<out_project>/cvat-functions:latest"}
23.08.14 14:29:15.608                     nuctl (W) Function creation failed, updating function status {"errorStack": "\nError - NuclioFunction in error state:\n\nError - NuclioFunction pod (nuclio-pth-facebookresearch-sam-vit-h-333-6947d698f5-6hnks) is in a crash loop\n    ...//nuclio/pkg/platform/kube/functionres/lazy.go:2702\n\nCall stack:\nNuclioFunction pod (nuclio-pth-facebookresearch-sam-vit-h-6947d698f5-6hnks) is in a crash loop\n    ...//nuclio/pkg/platform/kube/functionres/lazy.go:2702\nNuclioFunction deployment failed\n    ...//nuclio/pkg/platform/kube/functionres/lazy.go:566\nFailed to wait for function deployment readiness\n    ...//nuclio/pkg/platform/kube/functionres/lazy.go:353\nFailed to wait for function resources to be available\n    .../platform/kube/controller/nucliofunction.go:232\n\n    ...//nuclio/pkg/platform/kube/client/deployer.go:569\n\nCall stack:\nNuclioFunction in error state:\n\nError - NuclioFunction pod (nuclio-pth-facebookresearch-sam-vit-h-6947d698f5-6hnks) is in a crash loop\n    ...//nuclio/pkg/platform/kube/functionres/lazy.go:2702\n\nCall stack:\nNuclioFunction pod (nuclio-pth-facebookresearch-sam-vit-h-6947d698f5-6hnks) is in a crash loop\n    ...//nuclio/pkg/platform/kube/functionres/lazy.go:2702\nNuclioFunction deployment failed\n    ...//nuclio/pkg/platform/kube/functionres/lazy.go:566\nFailed to wait for function deployment readiness\n    ...//nuclio/pkg/platform/kube/functionres/lazy.go:353\nFailed to wait for function resources to be available\n    .../platform/kube/controller/nucliofunction.go:232\n\n    ...//nuclio/pkg/platform/kube/client/deployer.go:569\nFailed to wait for function readiness.\n\nPod logs:\n\n* nuclio-pth-facebookresearch-sam-vit-h-6947d698f5-6hnks\n23.08.14 14:29:12.769 \u001b[37m                processor\u001b[0m \u001b[34m(I)\u001b[0m Starting processor {\"version\": \"Label: 1.11.24, Git commit: f2a3900d23b92fd3639dc9cb765044ef53a4fb2b, OS: linux, Arch: amd64, Go version: go1.19.11\"}\n23.08.14 14:29:12.769 \u001b[37m                processor\u001b[0m \u001b[32m(D)\u001b[0m Read configuration {\"config\": \"{\n    \"metadata\": {\n        \"name\": \"pth-facebookresearch-sam-vit-h\",\n        \"namespace\": \"cvat\",\n        \"labels\": {\n            \"nuclio.io/app\": \"functionres\",\n            \"nuclio.io/class\": \"function\",\n            \"nuclio.io/function-name\": \"pth-facebookresearch-sam-vit-h\",\n            \"nuclio.io/function-version\": \"latest\",\n            \"nuclio.io/project-name\": \"cvat\"\n        },\n        \"annotations\": {\n            \"animated_gif\": \"https://raw.githubusercontent.com/opencv/cvat/develop/site/content/en/images/hrnet_example.gif\",\n            \"framework\": \"pytorch\",\n            \"help_message\": \"The interactor allows to get a mask of an object using at least one positive, and any negative points inside it\",\n            \"min_neg_points\": \"0\",\n            \"min_pos_points\": \"1\",\n            \"name\": \"Segment Anything\",\n            \"spec\": \"\",\n            \"type\": \"interactor\",\n            \"version\": \"2\"\n        }\n    },\n    \"spec\": {\n        \"description\": \"Interactive object segmentation with Segment-Anything\",\n        \"handler\": \"main:handler\",\n        \"runtime\": \"python:3.8\",\n        \"env\": [\n            {\n                \"name\": \"PYTHONPATH\",\n                \"value\": \"/opt/nuclio/sam\"\n            }\n        ],\n        \"resources\": {\n            \"requests\": {\n                \"cpu\": \"25m\",\n                \"memory\": \"1Mi\"\n            }\n        },\n        \"image\": \"<out_project>/cvat-functions:latest\",\n        \"imageHash\": \"1692023345375010221\",\n        \"targetCPU\": 75,\n        \"triggers\": {\n            \"myHttpTrigger\": {\n                \"class\": \"\",\n                \"kind\": \"http\",\n                \"name\": \"myHttpTrigger\",\n                \"maxWorkers\": 1,\n                \"workerAvailabilityTimeoutMilliseconds\": 10000,\n                \"attributes\": {\n                    \"maxRequestBodySize\": 33554432,\n                    \"serviceType\": \"ClusterIP\"\n                }\n            }\n        },\n        \"version\": -1,\n        \"alias\": \"latest\",\n        \"build\": {\n            \"functionConfigPath\": \"serverless/pytorch/facebookresearch/sam/nuclio/function.yaml\",\n            \"image\": \"<out_project>/cvat-functions\",\n            \"baseImage\": \"ubuntu:22.04\",\n            \"directives\": {\n                \"preCopy\": [\n                    {\n                        \"kind\": \"ENV\",\n                        \"value\": \"DEBIAN_FRONTEND=noninteractive\"\n                    },\n                    {\n                        \"kind\": \"WORKDIR\",\n                        \"value\": \"/opt/nuclio/sam\"\n                    },\n                    {\n                        \"kind\": \"RUN\",\n                        \"value\": \"apt-get update \\u0026\\u0026 apt-get -y install curl git python3 python3-pip ffmpeg libsm6 libxext6\"\n                    },\n                    {\n                        \"kind\": \"RUN\",\n                        \"value\": \"pip3 install torch torchvision torchaudio opencv-python pycocotools matplotlib onnxruntime onnx\"\n                    },\n                    {\n                        \"kind\": \"RUN\",\n                        \"value\": \"pip3 install git+https://github.com/facebookresearch/segment-anything.git\"\n                    },\n                    {\n                        \"kind\": \"RUN\",\n                        \"value\": \"curl -O https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth\"\n                    },\n                    {\n                        \"kind\": \"RUN\",\n                        \"value\": \"ln -s /usr/bin/pip3 /usr/local/bin/pip \\u0026\\u0026 ln -s /usr/bin/python3 /usr/bin/python\"\n                    }\n                ]\n            },\n            \"codeEntryType\": \"image\",\n            \"timestamp\": 1692023349\n        },\n        \"platform\": {\n            \"attributes\": {\n                \"mountMode\": \"volume\",\n                \"restartPolicy\": {\n                    \"maximumRetryCount\": 3,\n                    \"name\": \"always\"\n                }\n            }\n        },\n        \"readinessTimeoutSeconds\": 120,\n        \"securityContext\": {},\n        \"eventTimeout\": \"30s\"\n    },\n    \"PlatformConfig\": null\n}\"}\n23.08.14 14:29:12.769 \u001b[37mcessor.healthcheck.server\u001b[0m \u001b[34m(I)\u001b[0m Listening {\"listenAddress\": \":8082\"}\n23.08.14 14:29:12.770 \u001b[37m           processor.http\u001b[0m \u001b[32m(D)\u001b[0m Creating worker pool {\"num\": 1}\n23.08.14 14:29:12.770 \u001b[37msor.http.w0.python.logger\u001b[0m \u001b[32m(D)\u001b[0m Creating listener socket {\"path\": \"/tmp/nuclio-rpc-cjd3ke07jnpc73c51ra0.sock\"}\n23.08.14 14:29:12.770 \u001b[37msor.http.w0.python.logger\u001b[0m \u001b[32m(D)\u001b[0m Creating listener socket {\"path\": \"/tmp/nuclio-rpc-cjd3ke07jnpc73c51rag.sock\"}\n23.08.14 14:29:12.770 \u001b[37msor.http.w0.python.logger\u001b[0m \u001b[32m(D)\u001b[0m Using Python wrapper script path {\"path\": \"/opt/nuclio/_nuclio_wrapper.py\"}\n23.08.14 14:29:12.770 \u001b[37msor.http.w0.python.logger\u001b[0m \u001b[32m(D)\u001b[0m Using Python handler {\"handler\": \"main:handler\"}\n23.08.14 14:29:12.770 \u001b[37msor.http.w0.python.logger\u001b[0m \u001b[32m(D)\u001b[0m Using Python executable {\"path\": \"/usr/bin/python3\"}\n23.08.14 14:29:12.770 \u001b[37msor.http.w0.python.logger\u001b[0m \u001b[32m(D)\u001b[0m Setting PYTHONPATH {\"value\": \"PYTHONPATH=/opt/nuclio:/opt/nuclio/sam\"}\n23.08.14 14:29:12.770 \u001b[37msor.http.w0.python.logger\u001b[0m \u001b[32m(D)\u001b[0m Running wrapper {\"command\": \"/usr/bin/python3 -u /opt/nuclio/_nuclio_wrapper.py --handler main:handler --event-socket-path /tmp/nuclio-rpc-cjd3ke07jnpc73c51ra0.sock --control-socket-path /tmp/nuclio-rpc-cjd3ke07jnpc73c51rag.sock --platform-kind kube --namespace cvat --worker-id 0 --trigger-kind http --trigger-name myHttpTrigger --decode-event-strings\"}\n\nError - fork/exec /usr/bin/python3: exec format error\n    .../nuclio/pkg/processor/runtime/rpc/abstract.go:291\n\nCall stack:\nCan't run wrapper\n    .../nuclio/pkg/processor/runtime/rpc/abstract.go:291\nFailed to run wrapper\n    .../nuclio/pkg/processor/runtime/rpc/abstract.go:116\nFailed to start runtime\n    .../nuclio/nuclio/pkg/processor/worker/factory.go:100\nFailed to create worker\n    .../nuclio/nuclio/pkg/processor/worker/factory.go:119\nFailed to create workers\n    .../nuclio/nuclio/pkg/processor/worker/factory.go:129\n\n    ...//nuclio/pkg/platform/kube/client/deployer.go:154\n"}
23.08.14 14:29:15.627    nuctl.platform.updater (I) Updating function {"name": "pth-facebookresearch-sam-vit-h"}
​
Error - NuclioFunction in error state:
​
Error - NuclioFunction pod (nuclio-pth-facebookresearch-sam-vit-h-6947d698f5-6hnks) is in a crash loop
    ...//nuclio/pkg/platform/kube/functionres/lazy.go:2702
​
Call stack:
NuclioFunction pod (nuclio-pth-facebookresearch-sam-vit-h-6947d698f5-6hnks) is in a crash loop
    ...//nuclio/pkg/platform/kube/functionres/lazy.go:2702
NuclioFunction deployment failed
    ...//nuclio/pkg/platform/kube/functionres/lazy.go:566
Failed to wait for function deployment readiness
    ...//nuc...
```
