### ISSUE TITLE
Using serverless functions optimally within the local network (A hybrid approach using Docker and K8s)

### ISSUE THREAD

**Issue by ganindu7** [opencv/cvat#6714]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

#### I have run the serverless compose file on the cvat repo, therefore at port 8070 I can see the nuclio dashboard.

![Screenshot from 2023-08-21 10-11-55](https://github.com/opencv/cvat/assets/5096658/bcadf108-0f09-45e8-a7c0-9564bc7dfcf2)

#### within cvat (port 8080) models tab I can see the serverless functon.

![Screenshot from 2023-08-21 10-07-36](https://github.com/opencv/cvat/assets/5096658/b9d130b6-015a-4325-9f8c-f263bdb1561f)

This is all working fine and I can do auto annotation without a problem for the function hosted in the doocker server. 

However my cvat server doe not have a GPU so I can't run gpu serverless functions on that particular server. Luckily in  the same local network there is a small kubnernetes cluster that has a handful of nodes where one of them happens to be a GPU node.

```
K8 cluster

Master node-¬
             |- cpu node 1
             |- cpu node 2
             |- gpu node 1
             |- ...
```   

I installed nuclio on my local k8 cluster and I was able to sucessfully run serverless functions. 
  
![Screenshot from 2023-08-21 10-38-40](https://github.com/opencv/cvat/assets/5096658/8f2f7adf-216d-4ce8-9e00-c23919a091b3)

Then I verfied that my serverless functions are working properly utilising the gpu resources avaialble and tested wth a test web app written ro run on my pc (sending an image, recieving annotations, plotting and listing the returned annotations)

 
![Screenshot from 2023-08-21 10-38-17](https://github.com/opencv/cvat/assets/5096658/ee888057-c577-4400-96a9-4a5f1a567abb)

Note: *My PC running the function testing web app is not in the k8 cluster but in the same local network (I exposed the service(serverless function) as a nodeport so it can be accessed from outsuse the k8 cluster but within the same local network where my pc (and the cvat server) is in.*

### My aim, problem and possible solutions

Use the serverless function I created (in the k8 cluster) with the nuclio dashboard that is on the docker container (I doubt this is possible because the gpu operator is running on the k8 cluster and serverless functions are acting as K8 services (in k8 pods)  

or use the function as a URL (from my internet research this is a paid feature and can only be used with `cvat.ai`, this doesn;t suit me because I want to use everything locally (at least for now until I flesh out things)) 

or get CVAT to use my k8 nuclio dashboard (I don't understand this well so thi might be illogical) instead the dashboard from the severless docker compose file (I think this might be the most plausible if it make sense at all)
 
Can you pelase help me on this, 

Thanks,
Ganindu.

**Comment by stone100010** [comment]
The first computer name: Dell-8GPU, which contains 8*3090ti.
The second computer name: Dell-CPU, which is i7-13th.
I'm looking for a way:
Dell-CPU：severless cvat
Dell-8GPU：SAM
If you have any idea, please contact me. Thank you very much! ! !

**Comment by stone100010** [comment]
hi, open it: [https://nuclio.io/docs/latest/reference/triggers/http/#attributes](url)
(Kubernetes only) Kubernetes ServiceType, used by the Kubernetes service to expose the trigger. The default ServiceType is ClusterIP, which means that by default the trigger won't be exposed outside of the cluster unless you configure a proper ingress or manually change the ServiceType to NodePort.
Is it effective?

**Comment by ganindu7** [comment]
I think this issue is helpful here. 

@bsekachev Can you please advice us on this.

https://github.com/opencv/cvat/issues/2301

once I modify these vaibles 

```
NUCLIO = {
    'SCHEME': os.getenv('CVAT_NUCLIO_SCHEME', 'http'),
    'HOST': os.getenv('CVAT_NUCLIO_HOST', 'aisrv.gnet.lan'),
    'PORT': int(os.getenv('CVAT_NUCLIO_PORT', 30936)),
    'DEFAULT_TIMEOUT': int(os.getenv('CVAT_NUCLIO_DEFAULT_TIMEOUT', 120)),
    'FUNCTION_NAMESPACE': os.getenv('CVAT_NUCLIO_FUNCTION_NAMESPACE', 'nuclio'),
    'INVOKE_METHOD': os.getenv('CVAT_NUCLIO_INVOKE_METHOD',
        default='dashboard' if 'KUBERNETES_SERVICE_HOST' in os.environ else 'direct'),
}

```

do I need to have these in a seperate yaml ? 
```
  cvat_server:
    environment:
      CVAT_SERVERLESS: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cvat_worker_annotation:
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

**Comment by ganindu7** [comment]
> hi, open it: [https://nuclio.io/docs/latest/reference/triggers/http/#attributes](url) (Kubernetes only) Kubernetes ServiceType, used by the Kubernetes service to expose the trigger. The default ServiceType is ClusterIP, which means that by default the trigger won't be exposed outside of the cluster unless you configure a proper ingress or manually change the ServiceType to NodePort. Is it effective?

yes it is nodeport 

does that mean I have to specify  individual functions rather than the nuclio dashboard? (all this time i was putting my k8 nuclio dashboard URL and port for `CVAT_NUCLIO_HOST` and  `CVAT_NUCLIO_PORT` 

This is my nuclio dashboard from the k8 cluster 
![Screenshot from 2023-09-20 18-16-45](https://github.com/opencv/cvat/assets/5096658/bcbc919d-9612-49f7-aea4-feed9e7922f6)

**Comment by ganindu7** [comment]
finally I was able to make it work! 
I'm not sure where exactly was the problem was but here is what I did 

* I made sure the nuctl and nuclio server versions match. and I noticed that in cvat the nuctl version is appVersion: 1.8.14
but to get the matching helm chart we need to download the 1.8.15 release (maybe they forgot to update the helm chart)

[nuclio-1.8.15.zip](https://github.com/opencv/cvat/files/12685277/nuclio-1.8.15.zip)

my values yaml file
[values.yaml.txt](https://github.com/opencv/cvat/files/12685508/values.yaml.txt)

```
services:
  cvat_server:

    environment:
      CVAT_SERVERLESS: 1
      CVAT_NUCLIO_SCHEME: http  # Updated value
      CVAT_NUCLIO_HOST: aisrv.gnet.lan  # Updated value
      CVAT_NUCLIO_PORT: 30936 # Updated value
      KUBERNETES_SERVICE_HOST: true
      CVAT_NUCLIO_FUNCTION_NAMESPACE: nuclio

    volumes:
      - cvat_data:/home/django/data:rw

    extra_hosts:
      - "host.docker.internal:host-gateway"

  cvat_worker_annotation:
    extra_hosts:
      - "host.docker.internal:host-gateway"

```
my updates to cvat server. 

I understand that because I am not using the docker dashboard I may not need to use that specific version but at this point I just wanted things to work as the cvat team may have tested with the shipped version. 


(also remember to use docker-buildx)

**Comment by ganindu7** [comment]
This came back in release v2.7.6 again. despite me updating nuctl / nuclio images to 1.11.24 in all places (dashboard/, controller and nuctl)

this issue us very similar to  #[6582](https://github.com/opencv/cvat/issues/6582)

I commented with my temporary hack fix 

> I had the same problem after updating cvat.
> 
> My difference is cvat running from a docker container and nuclio running from a kubernetes cluster.
> 
> my deployment looks like this
> 
> ```
> (TAOPY) g@nvdgx:~/Workspace/sandbox/nuclio-serverless-sandbox/ganindu-tests$ ./deploy.sh nozzlenet_1/
> 23.10.17 10:17:33.441                     nuctl (I) Project created {"Name": "cvat", "Namespace": "nuclio"}
> Deploying . function...
> 23.10.17 10:17:33.561                     nuctl (I) Deploying function {"name": "test-nuctl-function-nozzlenet-1"}
> 23.10.17 10:17:33.566                     nuctl (I) Building {"builderKind": "docker", "versionInfo": "Label: 1.11.24, Git commit: f2a3900d23b92fd3639dc9cb765044ef53a4fb2b, OS: linux, Arch: amd64, Go version: go1.19.10", "name": "test-nuctl-function-nozzlenet-1"}
> 23.10.17 10:17:33.650                     nuctl (I) Staging files and preparing base images
> 23.10.17 10:17:33.678                     nuctl (I) Building processor image {"registryURL": "172.16.3.2:5000", "taggedImageName": "nozzlenet-nuclio-v1:latest"}
> 23.10.17 10:17:33.678     nuctl.platform.docker (I) Pulling image {"imageName": "quay.io/nuclio/handler-builder-python-onbuild:1.11.24-amd64"}
> 23.10.17 10:17:35.818            nuctl.platform (I) Building docker image {"image": "nozzlenet-nuclio-v1:latest"}
> 23.10.17 10:17:41.437            nuctl.platform (I) Pushing docker image into registry {"image": "nozzlenet-nuclio-v1:latest", "registry": "172.16.3.2:5000"}
> 23.10.17 10:17:41.437     nuctl.platform.docker (I) Pushing image {"from": "nozzlenet-nuclio-v1:latest", "to": "172.16.3.2:5000/nozzlenet-nuclio-v1:latest"}
> 23.10.17 10:17:42.850            nuctl.platform (I) Docker image was successfully built and pushed into docker registry {"image": "nozzlenet-nuclio-v1:latest"}
> 23.10.17 10:17:42.850                     nuctl (I) Build complete {"image": "nozzlenet-nuclio-v1:latest"}
> 23.10.17 10:17:50.882                     nuctl (I) Function deploy complete {"functionName": "test-nuctl-function-nozzlenet-1", "httpPort": 30555, "internalInvocationURLs": ["nuclio-test-nuctl-function-nozzlenet-1.nuclio.svc.cluster.local:8080"], "externalInvocationURLs": [":30555"]}
> 23.10.17 10:17:50.888    nuctl.platform.updater (I) Updating function {"name": "test-nuctl-function-nozzlenet-1"}
> 23.10.17 10:17:51.166    nuctl.platform.updater (I) Function updated {"functionName": "test-nuctl-function-nozzlenet-1"}
>  NAMESPACE | NAME                            | PROJECT | STATE | REPLICAS | NODE PORT 
>  nuclio    | test-nuctl-function-nozzlenet-1 | cvat    | ready | 1/1      | 30555     
> ```
> 
> as you can see mine uses ther nodepoprt `30555`
> 
> my `docker-compose-override.yaml' used to look like this
> 
> ```
> services:
>   cvat_server:
> 
>     environment:
>       CVAT_SERVERLESS: 1
>       CVAT_NUCLIO_SCHEME: "http"  # Updated value
>       CVAT_NUCLIO_HOST: "aisrv.gnet.lan"  # Updated value
>       CVAT_NUCLIO_PORT: 30936 # Updated value
>       KUBERNETES_SERVICE_HOST: "true"
>       CVAT_NUCLIO_FUNCTION_NAMESPACE: "nuclio"
> 
>     volumes:
>       - cvat_data:/home/django/data:rw
> 
>     extra_hosts:
>       - "host.docker.internal:host-gateway"
> 
>   cvat_worker_annotation:
>     extra_hosts:
>       - "host.docker.internal:host-gateway"
> 
> volumes:
>   cvat_data:
>     driver_opts:
>       type: none
>       device: /mnt/cvat_data
>       o: bind
> ```
> 
> and the error I was getting was (I will put only a part of it for brevity)
> 
> ```
> 2023-10-17 10:45:54,639 DEBG 'rqworker-annotation-0' stderr output:
> [2023-10-17 10:45:54,639] ERROR rq.worker: Traceback (most recent call last):
>   File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
>     conn = connection.create_connection(
>   File "/opt/venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
>     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
>   File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
>     httplib_response = self._make_request(
>   File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
>     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
>   File "/usr/lib/python3.10/http/client.py", line 1283, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
>     self.send(msg)
>   File "/usr/lib/python3.10/http/client.py", line 976, in send
>     self.connect()
>   File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
>     conn = self._new_conn()
>   File "/opt/venv/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
>     raise NewConnectionError(
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f20c8f38b80>: Failed to establish a new connection: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/venv/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
>     resp = conn.urlopen(
>   File "/opt/venv/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
>     retries = retries.increment(
>   File "/opt/venv/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=30555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20c8f38b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> ```
> 
> the intersting bit was where it seem to think the nodeport service was hosted in the docker host port 30555
> 
> ```
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='host.docker.internal', port=30555): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f20c8f38b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
> ```
> 
> so in a very dodgy way I modified the `docker-compse.override.yaml ` file to (which I know is wrong)
> 
> ```
>   cvat_worker_annotation:
>     extra_hosts:
>       - "host.docker.internal:172.16.1.19"
> ```
> 
> 172.16.1.19 is the ip address of my k8 control plane
> 
> and this partially fixed the issue (now I can automatically anotate jobs/projects) which I was not able to previously due to the error above (but it still does not work for individual images, times out to error 500)
> 
> I'm not a docker power user I just think the `fix` worked only because of some other potential error I made somewhere. can you please help me point out where could the original problem be.
> 
> Thanks

can somepjne plese suggest a better solutiuon. (I think my scenario is a combination of two wrongs now acting as a solution)

**Comment by kevle1** [comment]
Setting `KUBERNETES_SERVICE_HOST` will result in the `INVOKE_METHOD` being set to true for Nuclio which might have been the reason why issue was resolved. 

This may interest you: https://github.com/cvat-ai/cvat/issues/6797#issuecomment-2272616912

I was encountering similar issues~

**Comment by zwfcrazy** [comment]
I have figured out how to do this correctly. Before showing my solution, I want to say nuclio documentation is terrible.

---
Below is my solution.

There are two invocation methods: dashboard and direct. You can use both of them, but with different configuration. The default invocation method is direct, which invokes functions directly instead of via dashboard.

To invoke functions directly, you need to make sure functions' external invocation urls are available. Check this out: [exposing-a-function](https://docs.nuclio.io/en/1.13.x/tasks/deploying-functions.html#exposing-a-function)

The docker compose override you need for this invocation method is:
```
services:
  cvat_server:
    environment:
      CVAT_SERVERLESS: 1
      CVAT_NUCLIO_HOST: ${CVAT_NUCLIO_HOST:-localhost}
    extra_hosts:
      - "host.docker.internal:${CVAT_NUCLIO_HOST:-host-gateway}"  # required by AI Tools

  cvat_worker_annotation:
    extra_hosts:
      - "host.docker.internal:${CVAT_NUCLIO_HOST:-host-gateway}"  # required by automatic annotation
```
Note: you need to export CVAT_NUCLIO_HOST environment variable.

---
To invoke functions via dashboard, you need to make sure nuclio dashboard and those containers created by nuctl are  in the same docker network. This can be done with `network_mode: bridge` (may not be the best practice, see [how-to-join-the-default-bridge-network-with-docker-compose-v2](https://stackoverflow.com/questions/43754095/how-to-join-the-default-bridge-network-with-docker-compose-v2)).
```
services:
  nuclio:
    container_name: nuclio
    image: quay.io/nuclio/dashboard:1.13.0-amd64
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      http_proxy:
      https_proxy:
      no_proxy: ${no_proxy:-}
      NUCLIO_CHECK_FUNCTION_CONTAINERS_HEALTHINESS: 'true'
      NUCLIO_DASHBOARD_DEFAULT_FUNCTION_MOUNT_MODE: 'volume'
    ports:
      - '8070:8070'
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "3"
    network_mode: bridge   <---------------
```

The docker compose override you need for this invocation method is:
```
services:
  cvat_server:
    environment:
      CVAT_SERVERLESS: 1
      CVAT_NUCLIO_HOST: ${CVAT_NUCLIO_HOST:-localhost}
      CVAT_NUCLIO_INVOKE_METHOD: 'dashboard'

  cvat_worker_annotation:
    environment:
      CVAT_NUCLIO_HOST: ${CVAT_NUCLIO_HOST:-localhost}
      CVAT_NUCLIO_INVOKE_METHOD: 'dashboard'
```
