### ISSUE TITLE
Can not generate bounding box when I use customize yolov7 onnx model to do auto annotation

### ISSUE THREAD

**Issue by langerrrrrr** [opencv/cvat#6815]
Hi 

I want to use a 4 class customize detector to do auto annotation, I followed the default yolov7 structure and created folder like this:
I put function-gpu.yaml, main.py and model_handler.py under this directory.
![image](https://github.com/opencv/cvat/assets/144004783/553865c2-7307-43a3-8b86-c07814da2146)

I modify the number of class and model download link in function-gpu.yaml:

```
metadata:
  name: onnx-wongkinyiu-yolov7_weapon_1
  namespace: cvat
  annotations:
    name: YOLO v7 wp_1
    type: detector
    framework: onnx
    spec: |
      [
        { "id": 0, "name": "g_1" },
        { "id": 1, "name": "g_2" },
        { "id": 2, "name": "g_3" },
        { "id": 3, "name": "g_4" }
      ]
spec:
  description: YOLO v7 weapon via onnx-runtime
  runtime: 'python:3.8'
  handler: main:handler
  eventTimeout: 30s
  build:
    image: cvat.onnx.wongkinyiu.yolov7
    baseImage: ultralytics/yolov5:latest

    directives:
      preCopy:
        - kind: USER
          value: root
        - kind: RUN
          value: apt update && apt install --no-install-recommends -y libglib2.0-0 wget
        - kind: WORKDIR
          value: /opt/nuclio
        - kind: RUN
          value: pip install onnxruntime
        - kind: WORKDIR
          value: /opt/nuclio
        - kind: RUN
          value: wget https://huggingface.co/langerr/yolo_test/resolve/main/21_8_2023_weapon_16.onnx
        - kind: RUN
          value: ln -s /usr/bin/python3 /usr/bin/python

  triggers:
    myHttpTrigger:
      maxWorkers: 1
      kind: 'http'
      workerAvailabilityTimeoutMilliseconds: 10000
      attributes:
        maxRequestBodySize: 33554432 # 32MB

  resources:
    limits:
      nvidia.com/gpu: 1

  platform:
    attributes:
      restartPolicy:
        name: always
        maximumRetryCount: 3
      mountMode: volume
```
After that I run command `./serverless/deploy_gpu.sh ./serverless/customize/yolov7_weapon/` to build, it looks built successfully
![image](https://github.com/opencv/cvat/assets/144004783/d22600c2-acfd-499b-bacd-5d4e9c1424cd)
the first and last function is default yolov7 and yolv5 model, both can works well. The function in middle is what I added, this one doesn't work.

In cvat page, I can find the newly added model and the class number is correct as and the annotation progress bar looks noraml as well.
![image](https://github.com/opencv/cvat/assets/144004783/06ea939e-b693-4f0e-8a1c-e87a3365d8cb)
![image](https://github.com/opencv/cvat/assets/144004783/62549a2a-d802-4562-8a99-6cef46674797)
![image](https://github.com/opencv/cvat/assets/144004783/b7c01fc6-cde0-4f6e-9298-8754bf2ff918)

After the annotation finished, there is no annotation(bounding box) in the task. May I know any possible reasons? Thanks

FYI, `main.py` and `model_handler.py` are here:

main.py

```
import base64
import io
import json

import yaml
from model_handler import ModelHandler
from PIL import Image


def init_context(context):
    context.logger.info("Init context...  0%")

    # Read labels
    with open("/opt/nuclio/function.yaml", 'rb') as function_file:
        functionconfig = yaml.safe_load(function_file)

    labels_spec = functionconfig['metadata']['annotations']['spec']
    labels = {item['id']: item['name'] for item in json.loads(labels_spec)}

    # Read the DL model
    weights = '21_8_2023_weapon_16.onnx'
    model = ModelHandler(labels,weights)

    context.user_data.model = model

    context.logger.info("Init context...100%")


def handler(context, event):
    context.logger.info("Run YoloV7 ONNX model")
    data = event.body
    buf = io.BytesIO(base64.b64decode(data["image"]))
    threshold = float(data.get("threshold", 0.01))
    image = Image.open(buf)

    results = context.user_data.model.infer(image, threshold)

    return context.Response(body=json.dumps(results), headers={},
        content_type='application/json', status_code=200)
```
model_handler.py

```
# Copyright (C) 2023 CVAT.ai Corporation
#
# SPDX-License-Identifier: MIT

import cv2
import numpy as np
import onnxruntime as ort


class ModelHandler:
    def __init__(self, labels,weights):
        self.model = None
        self.load_network(model="21_8_2023_weapon_16.onnx")
        self.labels = labels


    def load_network(self, model):
        device = ort.get_device()
        cuda = True if device == 'GPU' else False
        try:
            providers = ['CUDAExecutionProvider', 'CPUExecutionProvider'] if cuda else ['CPUExecutionProvider']
            so = ort.SessionOptions()
            so.log_severity_level = 3

            self.model = ort.InferenceSession(model, providers=providers, sess_options=so)
            self.output_details = [i.name for i in self.model.get_outputs()]
            self.input_details = [i.name for i in self.model.get_inputs()]

            self.is_inititated = True
        except Exception as e:
            raise Exception(f"Cannot load model {model}: {e}")

    def letterbox(self, im, new_shape=(640, 640), color=(114, 114, 114), auto=True, scaleup=True, stride=32):
        # Resize and pad image while meeting stride-multiple constraints
        shape = im.shape[:2]  # current shape [height, width]
        if isinstance(new_shape, int):
            new_shape = (new_shape, new_shape)

        # Scale ratio (new / old)
        r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
        if not scaleup:  # only scale down, do not scale up (for better val mAP)
            r = min(r, 1.0)

        # Compute padding
        new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
        dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding

        if auto:  # minimum rectangle
            dw, dh = np.mod(dw, stride), np.mod(dh, stride)  # wh padding

        dw /= 2  # divide padding into 2 sides
        dh /= 2

        if shape[::-1] != new_unpad:  # resize
            im = cv2.resize(im, new_unpad, interpolation=cv2.INTER_LINEAR)
        top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
        left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
        im = cv2.copyMakeBorder(im, top, bottom, left, right, cv2.BORDER_CONSTANT, value=color)  # add border
        return im, r, (dw, dh)

    def _infer(self, inputs: np.ndarray):
        try:
            img = cv2.cvtColor(inputs, cv2.COLOR_BGR2RGB)
            image = img.copy()
            image, ratio, dwdh = self.letterbox(image, auto=False)
            image = image.transpose((2, 0, 1))
            image = np.expand_dims(image, 0)
            image = np.ascontiguousarray(image)

            im = image.astype(np.float32)
            im /= 255

            inp = {self.input_details[0]: im}
            # ONNX inference
            output = list()
            detections = self.model.run(self.output_details, inp)[0]

            # for det in detections:
            boxes = detections[:, 1:5]
            labels = detections[:, 5]
            scores = detections[:, -1]

            boxes -= np.array(dwdh * 2)
            boxes /= ratio
            boxes = boxes.round().astype(np.int32)
            output.append(boxes)
            output.append(labels)
            output.append(scores)
            return output

        except Exception as e:
            print(e)

    def infer(self, image, threshold):
        image = np.array(image)
        image = image[:, :, ::-1].copy()
        h, w, _ = image.shape
        detections = self._infer(image)

        results = []
        if detections:
            boxes = detections[0]
            labels = detections[1]
            scores = detections[2]

            for label, score, box in zip(labels, scores, boxes):
                if score >= threshold:
                    xtl = max(int(box[0]), 0)
                    ytl = max(int(box[1]), 0)
                    xbr = min(int(box[2]), w)
                    ybr = min(int(box[3]), h)

                    results.append({
                        "confidence": str(score),
                        "label": self.labels.get(label, "unknown"),
                        "points": [xtl, ytl, xbr, ybr],
                        "type": "rectangle",
                    })

        return results

```
