### ISSUE TITLE
Store Images and Annotations to different directory

### ISSUE THREAD

**Issue by SathvikKS** [opencv/cvat#6889]
What is the correct way to store the images and annotations in different directories? 
As per the docs, the data are stored in ```cvat_data``` and ```cvat_db``` respectively. So I edited the compose file to point to the volumes as
```
volumes:
  cvat_db:
    driver_opts:
        type: none
        device: /gdrive/Docker/CVAT/cvat_dv
        o: bind
  cvat_data:
    driver_opts:
        type: none
        device: /gdrive/Docker/CVAT/cvat_data
        o: bind
  cvat_keys:
  cvat_logs:
  cvat_events_db:
  cvat_cache_db:
```
where the ```/gdrive``` is mounted to my google drive using ```google-drive-ocamlfuse``` with permission set properly. I see the files in cvat_db being created in my drive but I cannot access the UI as I get ```Cannot connect to the server.``` on the webpage.
I have also seen this in the FAQ
```
services:
  cvat_server:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_import:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_export:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_annotation:
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
  cvat_share:
    driver_opts:
      type: none
      device: /d/my_cvat_share
      o: bind
```
but I think this is used to access existing images in the mount, whereas I want to store the uploaded pictures and their annotations in different folders to prevent my VM's disk utilization. Am I doing something wrong?
