### ISSUE TITLE
Unable to mount share file

### ISSUE THREAD

**Issue by Q-Tran** [opencv/cvat#6924]
My actions before raising this issue

    [√] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
    [√] Searched [past issues](https://github.com/issues)

Expected Behaviour

mount local volume to cvat_share
Current Behaviour

I followed the tutorial to create the override file at "https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path". However, when running I seem to still getting the following error:

Error response from daemon: failed to mount local volume: mount /mnt/share:/var/lib/docker/volumes/cvat_cvat_share/_data, flags: 0x1000: no such file or directory.

I'm not really sure why  the  file still shows /mnt/share as  the path is neither in the original yml or override yml file. I  have edited the override yml file to be invalid and  it will throw me an error, so the override file is being processed, but somehow it isn't reading the right mount volume. Any ideas on why or how to fix this?

Here is my docker-compose.override.yml file and it is in the cvat folder with docker-compose.yml file.

```
services:
  cvat_server:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_import:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_export:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_annotation:
    volumes:
      - cvat_share:/home/django/share:ro

volumes:
    cvat_share:
        driver_opts:
            type: none
            device: /f/Videos/share
            o: bind
```
