### ISSUE TITLE
No Data shown in Connected file share when AWS S3 is mounted

### ISSUE THREAD

**Issue by jinju2828** [opencv/cvat#7059]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

Hi everyone, I'm using self hosted CVAT. I find it really useful for our data training.
I mounted S3 into filesystem in our machine. And I tried to create task using `Connect file share tab`.
I followed [this instruction ](https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path)and created `docker-compose.override.yml `

```
 services:
  cvat_server:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_import:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_export:
    volumes:
      - cvat_share:/home/django/share:ro
  cvat_worker_annotation:
    volumes:
      - cvat_share:/home/django/share:ro
  traefik:
    ports:
      - 80:8080

 volumes:
   cvat_share:
     driver_opts:
       type: none
       device: /s3/{bucket name}
       o: bind

```
I found some similar issues, and tried their solutions which suggested creating volume and telling docker to search for a volume created externally, but I got no luck.
<img width="810" alt="image" src="https://github.com/opencv/cvat/assets/32770259/af0e8faa-fa2b-4075-92c6-6f9a260a910a">

And when I click `Connect file share tab` and  run docker logs it shows this log
```
2023-10-24 23:22:54,710 DEBG 'uvicorn-0' stdout output:
INFO:     12.139.160.171:0 - "GET /api/server/share?org=&directory=%2F HTTP/1.0" 200 OK
```

It's really hard to debug because there is no error message.

### Expected Behavior

It should show files under the directory /s3/{bucket name} when clicking `Connected file share` tab.

### Context

We want to upload task using our machine local storage which has been mounted S3. Right now we only tested creating task using `My computer `tab and now for scalability we want to create task from mounted files. Any help would be very appreciated!

### Environment

```Markdown
- Git hash commit:
commit 6e1c80c974e80271a0685a91a6f5e48c0ac7bc2f (HEAD -> develop, origin/develop)

- Docker version: 24.0.2

- Are you using Docker Swarm or Kubernetes? No

- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu 22.04.2 LTS (GNU/Linux 5.19.0-1027-aws x86_64)
```
