### ISSUE TITLE
Email_backend not configured despite environment variable being set

### ISSUE THREAD

**Issue by Farenweh** [opencv/cvat#7436]
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

0: Deploy CVAT step by step under the guidence of official Docs, with Docker and on Ubuntu;
1: Modify docker-compose.yml, like this:
```
cvat_server:
    container_name: cvat_server
    image: cvat/server:${CVAT_VERSION:-dev}
    ......
    environment:
      <<: *backend-env
      ......
      # fixme email
      EMAIL_HOST: smtp.qq.com
      EMAIL_PORT: 465
      EMAIL_USE_SSL: True
      EMAIL_HOST_USER: 123456789@qq.com
      EMAIL_HOST_PASSWORD: EMAIL_HOST_PASSWORD
      # EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend' # Tried but 
      EMAIL_BACKEND : 'django.core.mail.backends.console.EmailBackend' 
      ......
```
2: Create an orgnization and invite a guy, try sending an email.
3: Fail to send and get “Email backend is not configured.”

I have confirmed that the environment variable is set correctly inside the Docker container by using the command `printenv | grep EMAIL_BACKEND`, which returns the expected output: `EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend`.
However, when I inspect the logs (by using `docker logs cvat_server`) after a failed email attempt, I see the following error message:
`[2024-02-04 18:08:10,859] ERROR django.request: Internal Server Error: /api/invitations/3SGAVXioLEGqTkPZBTyuWi4TkESbJlzTkSWnsSe1MhRDpEyTAzpOXHl4OHUrLnkh/resend`
I have tried restarting the CVAT service and the Docker container, but the issue persists. I have also checked the cvat/settings/base.py file inside the container, and it appears that the EMAIL_BACKEND is set to None, which I believe is the default value and should be overridden by the environment variable.
I am using the Docker deployment method and have ensured that all dependencies are installed according to the official CVAT documentation. I have not made any custom modifications to the CVAT codebase.

### Expected Behavior

Just send invitation email successfully.

### Possible Solution

Tried modifing base.py/email_settings.py/docker-compose.yml (simply adding my email config to it/them), but nothing changed.

### Environment

```Markdown
git log -1
commit b7cc5627daa04958ed045e4b3fe9fd68ec3c9e01 (HEAD -> develop, origin/develop, origin/HEAD)
Author: Boris Sekachev <boris.sekachev@yandex.ru>
Date:   Fri Feb 2 00:03:11 2024 +0200

lsb_release -a 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

docker version
Client: Docker Engine - Community
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Thu Feb  1 00:23:19 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:19 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
