### ISSUE TITLE
Can I use another than 8080 port for already insalled cvat?

### ISSUE THREAD

**Issue by MaratZakirov** [opencv/cvat#845]
.

**Comment by clydebailey** [comment]
You can pass the port in the docker-compose.yml file as an argument.  Change 8080 from ports in cvat directive in the docker-compose.yml and do a docker-compose up -d.

**Comment by MaratZakirov** [comment]
> You can pass the port in the docker-compose.yml file as an argument. Change 8080 from ports in cvat directive in the docker-compose.yml and do a docker-compose up -d.

What should I write instead?

```
  cvat:
    container_name: cvat
    image: cvat
    restart: always
    depends_on:
      - cvat_redis
      - cvat_db
    ports:
      - "8080:8080"
    build:
```
